[package]
name         = "swed_io"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
description  = "Shipwrecked I/O — file reading with CP1252/UTF-8 encoding detection"

[dependencies]
swed_co     = { workspace = true }
swed_rt     = { workspace = true }
encoding_rs = { workspace = true }

[lints]
workspace = true
