// swed_rt/src/lib.rs
// Shipwrecked Runtime Library
//
// This crate is the runtime dependency of ALL code generated by `swed`.
// Generated .rs files begin with:
//   use swed_rt::{HbValue, HbArray};
//
// Public surface is intentionally flat — generated code uses simple names.

pub mod array;
pub mod builtins;
pub mod value;

// ---------------------------------------------------------------------------
// Flat re-exports — what generated code sees
// ---------------------------------------------------------------------------

pub use array::HbArray;
pub use value::HbValue;

// Built-in functions — generated code calls these as free functions.
pub use builtins::{
    // String
    hb_len, hb_alltrim, hb_ltrim, hb_rtrim,
    hb_upper, hb_lower,
    hb_substr, hb_at, hb_rat,
    hb_str, hb_val,
    hb_chr, hb_asc,
    hb_space, hb_replicate,
    hb_padr, hb_padl,
    // Numeric
    hb_int, hb_abs, hb_round,
    hb_max, hb_min,
    // Type
    hb_valtype, hb_empty, hb_isnil,
    // FOR loop iterator
    hb_range,
    // Macro
    hb_macro,
    // I/O
    hb_qout, hb_qqout,
    // Array free-functions
    hb_aadd, hb_asize, hb_ascan,
};

// ---------------------------------------------------------------------------
// hb_instr — free-function form of the `$` operator
// ---------------------------------------------------------------------------

/// `needle $ haystack` — true if needle is a substring of haystack.
pub fn hb_instr(needle: HbValue, haystack: HbValue) -> HbValue {
    needle.hb_instr_contains(&haystack)
}

// ---------------------------------------------------------------------------
// Convenience macro for array literals in generated code
//
//   Harbour:  { 1, 2, 3 }
//   Rust:     hb_array![ HbValue::Integer(1), HbValue::Integer(2), ... ]
// ---------------------------------------------------------------------------

#[macro_export]
macro_rules! hb_array {
    ( $($e:expr),* $(,)? ) => {{
        let mut __a = $crate::HbArray::new();
        $( __a.hb_aadd($e); )*
        __a
    }};
}

// ---------------------------------------------------------------------------
// Crate-level tests (integration)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hb_array_macro() {
        let a = hb_array![
            HbValue::Integer(1),
            HbValue::String("two".into()),
            HbValue::Logical(true),
        ];
        assert_eq!(a.len(), 3);
        assert_eq!(a.hb_get(2), HbValue::String("two".into()));
    }

    #[test]
    fn test_hb_instr() {
        assert_eq!(
            hb_instr(HbValue::String("lo".into()), HbValue::String("Hello".into())),
            HbValue::Logical(true)
        );
        assert_eq!(
            hb_instr(HbValue::String("xyz".into()), HbValue::String("Hello".into())),
            HbValue::Logical(false)
        );
    }

    #[test]
    fn test_full_pipeline_snippet() {
        // Simulates what `swed` generates for:
        //   LOCAL aTeste := {}
        //   AAdd( aTeste, [Texto] )
        //   ? LEN( aTeste )
        let mut a_teste = HbArray::new();
        a_teste.hb_aadd(HbValue::String("Texto".into()));
        let n = hb_len(HbValue::Array(a_teste.clone()));
        assert_eq!(n, HbValue::Integer(1));
    }
}
