// swed/src/codegen.rs
// Code Generator: ast::Program → Rust source (String)
//
// Mapping strategy (Harbour → Rust):
//   PROCEDURE p()       →  fn p()  (returns ())
//   FUNCTION  f()       →  fn f() -> HbValue
//   LOCAL x := v        →  let mut x = v;
//   STATIC x := v       →  static X: Mutex<HbValue> = ...  (via OnceCell helper)
//   DO WHILE cond       →  while cond { ... }
//   FOR i := s TO e     →  for i in (s..=e)   (step-1 shortcut)
//   FOR i := s TO e STEP n →  { let mut i=s; while i<=e { ...; i+=n; } }
//   IF/ELSEIF/ELSE      →  if / else if / else
//   AAdd(a, v)          →  a.hb_aadd(v)
//   LEN(x)              →  x.len()
//   ?  expr             →  println!("{}", expr)
//   NIL                 →  HbValue::Nil
//   .T. / .F.           →  HbValue::Logical(true/false)
//   [string]            →  HbValue::String("string".into())
//   { e1, e2 }          →  hb_array![ e1, e2 ]   (macro defined in preamble)

use std::collections::HashSet;
use crate::ast::{
    AtGetStmt, AtSayStmt, BinOp, CallExpr, ClassDef, Expr, ExprKind, FuncDef,
    Param, ProcDef, Program, Stmt, StmtKind, TopLevel, UnOp,
};
use crate::scope::to_snake_case;

// ---------------------------------------------------------------------------
// Codegen context
// ---------------------------------------------------------------------------

pub struct Codegen {
    indent: usize,
    out: String,
    /// Nomes PUBLIC (módulo inteiro). Emite `public_store()`.
    public_names: HashSet<String>,
    /// Nomes FIELD da unidade atual. Emite `field_get()`/`field_set()`.
    /// Prioridade: FIELD > MEMVAR/PUBLIC (mas abaixo de LOCAL/STATIC).
    field_names: HashSet<String>,
    /// Funções livres de `swed_rt` detectadas na AST (hb_range, hb_str, …).
    rt_fns: HashSet<String>,
    /// Funções livres de `swed_bf` detectadas na AST (hb_strzero, hb_ntos, …).
    bf_fns: HashSet<String>,
}

impl Codegen {
    pub fn new() -> Self {
        Codegen {
            indent: 0,
            out: String::new(),
            public_names: HashSet::new(),
            field_names: HashSet::new(),
            rt_fns: HashSet::new(),
            bf_fns: HashSet::new(),
        }
    }

    // ── Output helpers ───────────────────────────────────────────────────

    fn line(&mut self, s: &str) {
        let pad = "    ".repeat(self.indent);
        self.out.push_str(&pad);
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) {
        self.out.push('\n');
    }

    fn push(&mut self, s: &str) {
        self.out.push_str(s);
    }

    fn indent(&mut self)   { self.indent += 1; }
    fn dedent(&mut self)   { if self.indent > 0 { self.indent -= 1; } }

    // -----------------------------------------------------------------------
    // Entry point
    // -----------------------------------------------------------------------

    pub fn generate(&mut self, program: &Program) -> String {
        self.scan_publics(program);
        self.scan_native_fns(program);
        self.emit_preamble(None);

        for unit in &program.units {
            self.blank();
            match unit {
                TopLevel::Procedure(p) => self.emit_proc(p),
                TopLevel::Function(f)  => self.emit_func(f),
                TopLevel::Class(c)     => self.emit_class(c),
            }
        }
        self.out.clone()
    }

    /// Gera dois arquivos: `(main_src, module_src)`.
    /// `main_src`   → `<stem>.rs`        — lógica transpilada com `use crate::<stem>_module::*;`
    /// `module_src` → `<stem>_module.rs` — prelude de pub use (HbValue, swed_bf, …)
    pub fn generate_with_module(&mut self, program: &Program, stem: &str) -> (String, String) {
        self.scan_publics(program);
        self.scan_native_fns(program);

        let module_src = self.build_module_src(stem);

        self.emit_preamble(Some(stem));
        for unit in &program.units {
            self.blank();
            match unit {
                TopLevel::Procedure(p) => self.emit_proc(p),
                TopLevel::Function(f)  => self.emit_func(f),
                TopLevel::Class(c)     => self.emit_class(c),
            }
        }
        (self.out.clone(), module_src)
    }

    /// Monta o conteúdo de `<stem>_module.rs` com os `pub use` detectados.
    fn build_module_src(&self, stem: &str) -> String {
        let mut m = String::new();
        m.push_str(&format!(
            "// Generated by SWed — {stem}_module.rs — do not edit manually.\n"
        ));
        m.push_str("#![allow(unused_imports)]\n\n");

        // Sempre presentes: tipos core e acesso a variáveis/campos
        m.push_str("pub use swed_rt::{HbValue, HbArray};\n");
        m.push_str("pub use swed_rt::publics_var::public_store;\n");
        m.push_str("pub use swed_db::{field_get, field_set};\n");

        // Funções de swed_rt detectadas na AST (ex: hb_range, hb_str, hb_instr)
        let mut rt: Vec<&str> = self.rt_fns.iter().map(String::as_str).collect();
        rt.sort_unstable();
        if !rt.is_empty() {
            m.push_str(&format!("pub use swed_rt::{{{}}};\n", rt.join(", ")));
        }

        // Funções de swed_bf detectadas na AST (ex: hb_strzero, hb_ntos, hb_date)
        let mut bf: Vec<&str> = self.bf_fns.iter().map(String::as_str).collect();
        bf.sort_unstable();
        if !bf.is_empty() {
            m.push_str(&format!("pub use swed_bf::{{{}}};\n", bf.join(", ")));
        }

        m
    }

    // -----------------------------------------------------------------------
    // Pré-scan: coleta nomes PUBLIC de todo o programa
    // -----------------------------------------------------------------------

    fn scan_publics(&mut self, program: &Program) {
        for unit in &program.units {
            let body: &[Stmt] = match unit {
                TopLevel::Procedure(p) => &p.body,
                TopLevel::Function(f)  => &f.body,
                TopLevel::Class(_)     => continue,
            };
            self.scan_stmts_publics(body);
        }
    }

    fn scan_stmts_publics(&mut self, stmts: &[Stmt]) {
        for s in stmts {
            match &s.kind {
                StmtKind::PublicDecl(d) => {
                    for v in &d.vars {
                        self.public_names.insert(v.name.to_ascii_uppercase());
                    }
                }
                StmtKind::If(i) => {
                    self.scan_stmts_publics(&i.then_body);
                    for (_, b) in &i.elseif_branches { self.scan_stmts_publics(b); }
                    if let Some(b) = &i.else_body { self.scan_stmts_publics(b); }
                }
                StmtKind::DoWhile(w) => self.scan_stmts_publics(&w.body),
                StmtKind::For(f)     => self.scan_stmts_publics(&f.body),
                _ => {}
            }
        }
    }

    /// Coleta nomes FIELD de um corpo de função — redefine `field_names`
    /// a cada unidade (FIELD é local ao escopo em que foi declarado).
    fn collect_field_names(&mut self, body: &[Stmt]) {
        self.field_names.clear();
        self.collect_fields_recursive(body);
    }

    fn collect_fields_recursive(&mut self, stmts: &[Stmt]) {
        for s in stmts {
            match &s.kind {
                StmtKind::FieldDecl { names, .. } => {
                    for n in names {
                        self.field_names.insert(n.to_ascii_uppercase());
                    }
                }
                StmtKind::If(i) => {
                    self.collect_fields_recursive(&i.then_body);
                    for (_, b) in &i.elseif_branches { self.collect_fields_recursive(b); }
                    if let Some(b) = &i.else_body { self.collect_fields_recursive(b); }
                }
                StmtKind::DoWhile(w) => self.collect_fields_recursive(&w.body),
                StmtKind::For(f)     => self.collect_fields_recursive(&f.body),
                _ => {}
            }
        }
    }

    // -----------------------------------------------------------------------
    // Pré-scan: detecta quais funções nativas (swed_rt / swed_bf) são usadas
    // -----------------------------------------------------------------------

    fn scan_native_fns(&mut self, program: &Program) {
        for unit in &program.units {
            match unit {
                TopLevel::Procedure(p) => self.scan_stmts_native(&p.body),
                TopLevel::Function(f)  => self.scan_stmts_native(&f.body),
                TopLevel::Class(c) => {
                    for m in &c.methods { self.scan_stmts_native(&m.body); }
                }
            }
        }
    }

    fn scan_stmts_native(&mut self, stmts: &[Stmt]) {
        for stmt in stmts { self.scan_stmt_native(stmt); }
    }

    fn scan_stmt_native(&mut self, stmt: &Stmt) {
        match &stmt.kind {
            StmtKind::VarDecl(d) | StmtKind::StaticDecl(d) | StmtKind::PublicDecl(d) => {
                for v in &d.vars {
                    if let Some(e) = &v.init { self.scan_expr_native(e); }
                }
            }
            StmtKind::Assign(a) => {
                self.scan_expr_native(&a.target);
                self.scan_expr_native(&a.value);
            }
            StmtKind::Call(c)  => self.scan_call_native(c),
            StmtKind::Print(e) => self.scan_expr_native(e),
            StmtKind::Return(Some(e)) => self.scan_expr_native(e),
            StmtKind::If(i) => {
                self.scan_expr_native(&i.condition);
                self.scan_stmts_native(&i.then_body);
                for (c, b) in &i.elseif_branches {
                    self.scan_expr_native(c);
                    self.scan_stmts_native(b);
                }
                if let Some(b) = &i.else_body { self.scan_stmts_native(b); }
            }
            StmtKind::DoWhile(w) => {
                self.scan_expr_native(&w.condition);
                self.scan_stmts_native(&w.body);
            }
            StmtKind::For(f) => {
                self.rt_fns.insert("hb_range".into());
                self.scan_expr_native(&f.start);
                self.scan_expr_native(&f.end);
                if let Some(step) = &f.step { self.scan_expr_native(step); }
                self.scan_stmts_native(&f.body);
            }
            StmtKind::AtSay(say) => {
                self.scan_expr_native(&say.row);
                self.scan_expr_native(&say.col);
                self.scan_expr_native(&say.expr);
            }
            StmtKind::AtGet(get) => {
                self.scan_expr_native(&get.row);
                self.scan_expr_native(&get.col);
            }
            StmtKind::MemvarDecl(_)
            | StmtKind::FieldDecl { .. }
            | StmtKind::Return(None)
            | StmtKind::Read => {}
        }
    }

    fn scan_expr_native(&mut self, expr: &Expr) {
        match &expr.kind {
            ExprKind::Call(c) => self.scan_call_native(c),
            ExprKind::BinOp(op, l, r) => {
                if op == &BinOp::InStr {
                    self.rt_fns.insert("hb_instr".into());
                }
                self.scan_expr_native(l);
                self.scan_expr_native(r);
            }
            ExprKind::UnOp(_, e) => self.scan_expr_native(e),
            ExprKind::Macro(_) => { self.rt_fns.insert("hb_macro".into()); }
            ExprKind::ArrayLit(elems) => {
                for e in elems { self.scan_expr_native(e); }
            }
            ExprKind::Index(a, i) => {
                self.scan_expr_native(a);
                self.scan_expr_native(i);
            }
            ExprKind::Field(o, _) => self.scan_expr_native(o),
            ExprKind::Iif(c, t, e) => {
                self.scan_expr_native(c);
                self.scan_expr_native(t);
                self.scan_expr_native(e);
            }
            ExprKind::Nil | ExprKind::Bool(_) | ExprKind::Integer(_)
            | ExprKind::Float(_) | ExprKind::String(_) | ExprKind::Ident(_) => {}
        }
    }

    fn scan_call_native(&mut self, call: &CallExpr) {
        match call.callee.as_str() {
            "STR"    if !call.args.is_empty()    => { self.rt_fns.insert("hb_str".into()); }
            "VAL"    if call.args.len() == 1     => { self.rt_fns.insert("hb_val".into()); }
            "SUBSTR"                              => { self.rt_fns.insert("hb_substr".into()); }
            "AT"     if call.args.len() == 2     => { self.rt_fns.insert("hb_at".into()); }
            _ => {}
        }
        for arg in &call.args { self.scan_expr_native(arg); }
    }

    // -----------------------------------------------------------------------
    // Preamble: use statements + HbValue/HbArray re-exports + macros
    // -----------------------------------------------------------------------

    fn emit_preamble(&mut self, module_stem: Option<&str>) {
        self.line("// Generated by SWed (Shipwrecked) — do not edit manually.");
        self.line("#![allow(non_snake_case, unused_mut, unused_variables, unused_imports)]");
        self.blank();
        match module_stem {
            Some(stem) => {
                // Dual-file: todo o ambiente vem do _module.rs gerado em paralelo
                self.line(&format!("use crate::{stem}_module::*;"));
            }
            None => {
                // Standalone/legacy (testes e run_demo): imports diretos
                self.line("use swed_rt::{HbValue, HbArray};");
                self.line("use swed_rt::publics_var::public_store;");
                self.line("use swed_db::{field_get, field_set};");
            }
        }
        self.blank();
        // Convenience macro for array literals  { 1, 2, 3 } → hb_array![...]
        self.line("macro_rules! hb_array {");
        self.indent();
        self.line("( $($e:expr),* $(,)? ) => {{");
        self.indent();
        self.line("let mut __a = HbArray::new();");
        self.line("$( __a.hb_aadd($e); )*");
        self.line("__a");
        self.dedent();
        self.line("}};");
        self.dedent();
        self.line("}");
    }

    // -----------------------------------------------------------------------
    // Procedure → fn name() { ... }
    // -----------------------------------------------------------------------

    fn emit_proc(&mut self, p: &ProcDef) {
        self.collect_field_names(&p.body);
        let fname = to_snake_case(&p.name);
        if p.name.to_ascii_uppercase() == "MAIN" {
            // Rust entry point: fn main() never takes parameters.
            // Harbour Main params come from the OS command line — bind them here.
            self.line("fn main() {");
            self.indent();
            if !p.params.is_empty() {
                self.line("let mut __args: Vec<HbValue> = std::env::args().skip(1)");
                self.line("    .map(|s| HbValue::String(s)).collect();");
                for (i, param) in p.params.iter().enumerate() {
                    let pname = to_snake_case(&param.name);
                    self.line(&format!(
                        "let mut {pname} = __args.get({i}).cloned().unwrap_or(HbValue::Nil);"
                    ));
                }
            }
        } else {
            let params = self.render_params(&p.params);
            self.line(&format!("fn {fname}({params}) {{"));
            self.indent();
        }
        self.emit_stmts(&p.body);
        self.dedent();
        self.line("}");
    }

    // -----------------------------------------------------------------------
    // Function → fn name(...) -> HbValue { ... }
    // -----------------------------------------------------------------------

    fn emit_func(&mut self, f: &FuncDef) {
        self.collect_field_names(&f.body);
        let params = self.render_params(&f.params);
        let fname = to_snake_case(&f.name);
        self.line(&format!("fn {fname}({params}) -> HbValue {{"));
        self.indent();
        self.emit_stmts(&f.body);
        // Ensure there is always a fallback return
        self.line("HbValue::Nil");
        self.dedent();
        self.line("}");
    }

    fn render_params(&self, params: &[Param]) -> String {
        params
            .iter()
            .map(|p| format!("mut {}: HbValue", to_snake_case(&p.name)))
            .collect::<Vec<_>>()
            .join(", ")
    }

    // -----------------------------------------------------------------------
    // Class → struct + impl block (skeleton)
    // -----------------------------------------------------------------------

    fn emit_class(&mut self, c: &ClassDef) {
        let sname = &c.name;
        self.line(&format!("// CLASS {sname}"));
        self.line(&format!("struct {sname} {{"));
        self.indent();
        for d in &c.data {
            let field = to_snake_case(&d.name);
            self.line(&format!("{field}: HbValue,"));
        }
        self.dedent();
        self.line("}");
        self.blank();
        self.line(&format!("impl {sname} {{"));
        self.indent();
        // Default constructor
        self.line("fn new() -> Self {");
        self.indent();
        self.line(&format!("{sname} {{"));
        self.indent();
        for d in &c.data {
            let field = to_snake_case(&d.name);
            self.line(&format!("{field}: HbValue::Nil,"));
        }
        self.dedent();
        self.line("}");
        self.dedent();
        self.line("}");
        // Methods
        for m in &c.methods {
            self.blank();
            let params = self.render_params(&m.params);
            let sep = if params.is_empty() { "".to_string() } else { format!(", {params}") };
            let mname = to_snake_case(&m.name);
            self.line(&format!("fn {mname}(&mut self{sep}) -> HbValue {{"));
            self.indent();
            self.emit_stmts(&m.body);
            self.line("HbValue::Nil");
            self.dedent();
            self.line("}");
        }
        self.dedent();
        self.line("}");
    }

    // -----------------------------------------------------------------------
    // Statements
    // -----------------------------------------------------------------------

    fn emit_stmts(&mut self, stmts: &[Stmt]) {
        let mut i = 0;
        while i < stmts.len() {
            match &stmts[i].kind {
                StmtKind::AtSay(_) | StmtKind::AtGet(_) => {
                    // Encontra o READ que fecha este bloco (inclusive)
                    let maybe_read = stmts[i..]
                        .iter()
                        .position(|s| matches!(s.kind, StmtKind::Read));
                    if let Some(rel) = maybe_read {
                        let end = i + rel + 1;
                        self.emit_read_block(&stmts[i..end]);
                        i = end;
                    } else {
                        // SAY sem READ → println simples; GET sem READ → ignorado
                        if let StmtKind::AtSay(say) = &stmts[i].kind {
                            let val = self.render_expr(&say.expr);
                            let pad = "    ".repeat(self.indent);
                            self.out.push_str(&format!("{pad}println!(\"{{}}\", {val});\n"));
                        }
                        i += 1;
                    }
                }
                StmtKind::Read => {
                    // READ sem @..GET precedente — ignorado
                    i += 1;
                }
                _ => {
                    self.emit_stmt(&stmts[i]);
                    i += 1;
                }
            }
        }
    }

    /// Emite um bloco scoped com AppState para o grupo SAY/GET...READ.
    fn emit_read_block(&mut self, stmts: &[Stmt]) {
        // Separa SAYs e GETs (preserva ordem dos GETs para o índice de retorno)
        let mut says: Vec<&AtSayStmt> = Vec::new();
        let mut gets: Vec<&AtGetStmt> = Vec::new();
        for s in stmts {
            match &s.kind {
                StmtKind::AtSay(say) => says.push(say),
                StmtKind::AtGet(get) => gets.push(get),
                _ => {}
            }
        }

        // Pré-computa labels e construtores de widget antes de mutar self.out
        let widgets: Vec<(String, String)> = gets
            .iter()
            .map(|get| {
                let label = find_say_label(get, &says);
                let ctor  = render_widget_ctor(get, &label);
                (to_snake_case(&get.var), ctor)
            })
            .collect();

        self.line("{");
        self.indent();

        // Importa swed_ui apenas no escopo do bloco — sem poluir o namespace global
        self.line("use swed_ui::{AppState, ReadResult, GetElement,");
        self.line("    CharInput, NumericInput, DateInput, LogicalToggle};");
        self.line("use swed_ui::widgets::char_input::Picture as HbPicture;");
        self.line("let mut __fields: Vec<Box<dyn GetElement>> = Vec::new();");

        for (snake, ctor) in &widgets {
            self.line("{");
            self.indent();
            self.line(&format!("let mut __f: Box<dyn GetElement> = Box::new({ctor});"));
            self.line(&format!("__f.set_value({snake}.clone());"));
            self.line("__fields.push(__f);");
            self.dedent();
            self.line("}");
        }

        self.line("match AppState::new(__fields).run() {");
        self.indent();
        self.line("Ok(ReadResult::Confirmed(__vals)) => {");
        self.indent();
        for (idx, (snake, _)) in widgets.iter().enumerate() {
            self.line(&format!("{snake} = __vals[{idx}].clone();"));
        }
        self.dedent();
        self.line("}");
        self.line("_ => {}");
        self.dedent();
        self.line("}");

        self.dedent();
        self.line("}");
    }

    fn emit_stmt(&mut self, stmt: &Stmt) {
        let pad = "    ".repeat(self.indent);
        match &stmt.kind {

            StmtKind::VarDecl(d) => {
                for v in &d.vars {
                    let name = to_snake_case(&v.name);
                    let init = v.init.as_ref()
                        .map(|e| self.render_expr(e))
                        .unwrap_or_else(|| "HbValue::Nil".into());
                    self.out.push_str(&format!("{pad}let mut {name} = {init};\n"));
                }
            }

            StmtKind::StaticDecl(d) => {
                // STATIC → thread_local! with RefCell
                for v in &d.vars {
                    let name = to_snake_case(&v.name).to_ascii_uppercase();
                    let init = v.init.as_ref()
                        .map(|e| self.render_expr(e))
                        .unwrap_or_else(|| "HbValue::Nil".into());
                    self.out.push_str(&format!(
                        "{pad}thread_local! {{ static {name}: std::cell::RefCell<HbValue> \
                         = std::cell::RefCell::new({init}); }}\n"
                    ));
                }
            }

            StmtKind::FieldDecl { .. } => {
                // FIELD é um mapeamento para a WorkArea; sem alocação de variável.
            }

            StmtKind::MemvarDecl(names) => {
                for n in names {
                    let rn = to_snake_case(n);
                    self.out.push_str(&format!("{pad}let mut {rn} = HbValue::Nil; // MEMVAR\n"));
                }
            }

            StmtKind::PublicDecl(d) => {
                // PUBLIC → armazém global; inicializador opcional
                for v in &d.vars {
                    let upper = v.name.to_ascii_uppercase();
                    let init = v.init.as_ref()
                        .map(|e| self.render_expr(e))
                        .unwrap_or_else(|| "HbValue::Nil".into());
                    self.out.push_str(&format!(
                        "{pad}public_store().write().unwrap().set(\"{upper}\", {init});\n"
                    ));
                }
            }

            StmtKind::Assign(a) => {
                if let ExprKind::Ident(name) = &a.target.kind {
                    let upper = name.to_ascii_uppercase();
                    // FIELD → escreve na WorkArea (prioridade sobre PUBLIC/MEMVAR)
                    if self.field_names.contains(&upper) {
                        let value = self.render_expr(&a.value);
                        self.out.push_str(&format!(
                            "{pad}field_set(\"{upper}\", {value});\n"
                        ));
                        return;
                    }
                    // PUBLIC → armazém global
                    if self.public_names.contains(&upper) {
                        let value = self.render_expr(&a.value);
                        self.out.push_str(&format!(
                            "{pad}public_store().write().unwrap().set(\"{upper}\", {value});\n"
                        ));
                        return;
                    }
                }
                let target = self.render_expr(&a.target);
                let value  = self.render_expr(&a.value);
                self.out.push_str(&format!("{pad}{target} = {value};\n"));
            }

            StmtKind::Call(c) => {
                let call = self.render_call(c);
                self.out.push_str(&format!("{pad}{call};\n"));
            }

            StmtKind::Print(e) => {
                let val = self.render_expr(e);
                self.out.push_str(&format!("{pad}println!(\"{{}}\", {val});\n"));
            }

            StmtKind::If(i) => {
                let cond = self.render_expr(&i.condition);
                self.out.push_str(&format!("{pad}if {cond} {{\n"));
                self.indent();
                self.emit_stmts(&i.then_body);
                self.dedent();
                for (ec, eb) in &i.elseif_branches {
                    let ec_r = self.render_expr(ec);
                    self.out.push_str(&format!("{pad}}} else if {ec_r} {{\n"));
                    self.indent();
                    self.emit_stmts(eb);
                    self.dedent();
                }
                if let Some(eb) = &i.else_body {
                    self.out.push_str(&format!("{pad}}} else {{\n"));
                    self.indent();
                    self.emit_stmts(eb);
                    self.dedent();
                }
                self.out.push_str(&format!("{pad}}}\n"));
            }

            StmtKind::DoWhile(w) => {
                let cond = self.render_expr(&w.condition);
                self.out.push_str(&format!("{pad}while {cond} {{\n"));
                self.indent();
                self.emit_stmts(&w.body);
                self.dedent();
                self.out.push_str(&format!("{pad}}}\n"));
            }

            StmtKind::For(f) => {
                let start = self.render_expr(&f.start);
                let end   = self.render_expr(&f.end);
                let var   = to_snake_case(&f.var);

                if f.step.is_none() {
                    // Simple STEP 1 case → idiomatic Rust range
                    self.out.push_str(&format!(
                        "{pad}for {var} in hb_range({start}, {end}, 1) {{\n"
                    ));
                } else {
                    let step = self.render_expr(f.step.as_ref().unwrap());
                    self.out.push_str(&format!(
                        "{pad}for {var} in hb_range({start}, {end}, {step}) {{\n"
                    ));
                }
                self.indent();
                self.emit_stmts(&f.body);
                self.dedent();
                self.out.push_str(&format!("{pad}}}\n"));
            }

            StmtKind::Return(e) => {
                match e {
                    Some(expr) => {
                        let val = self.render_expr(expr);
                        self.out.push_str(&format!("{pad}return {val};\n"));
                    }
                    None => self.out.push_str(&format!("{pad}return;\n")),
                }
            }

            // Tratados em lote por emit_stmts → emit_read_block
            StmtKind::AtSay(_) | StmtKind::AtGet(_) | StmtKind::Read => {}
        }
    }

    // -----------------------------------------------------------------------
    // Expressions → &str
    // -----------------------------------------------------------------------

    fn render_expr(&self, expr: &Expr) -> String {
        match &expr.kind {
            ExprKind::Nil               => "HbValue::Nil".into(),
            ExprKind::Bool(b)           => format!("HbValue::Logical({b})"),
            ExprKind::Integer(n)        => format!("HbValue::Integer({n})"),
            ExprKind::Float(f)          => format!("HbValue::Float({f})"),
            ExprKind::String(s)         => format!("HbValue::String(\"{}\".into())", s.replace('"', "\\\"")),
            ExprKind::Ident(name) => {
                let upper = name.to_ascii_uppercase();
                if self.field_names.contains(&upper) {
                    // FIELD → leitura dinâmica da WorkArea atual
                    format!("field_get(\"{upper}\")")
                } else if self.public_names.contains(&upper) {
                    format!("public_store().read().unwrap().get(\"{upper}\")")
                } else {
                    to_snake_case(name)
                }
            }
            ExprKind::Macro(name)       => format!("/*&*/hb_macro({})", to_snake_case(name)),

            ExprKind::ArrayLit(elems) => {
                let inner: Vec<String> = elems.iter().map(|e| self.render_expr(e)).collect();
                format!("hb_array![{}]", inner.join(", "))
            }

            ExprKind::Index(arr, idx) => {
                let a = self.render_expr(arr);
                let i = self.render_expr(idx);
                // HbValue is not Copy; clone so the index variable stays usable after this call
                format!("{a}.hb_get_val({i}.clone())")
            }

            ExprKind::Field(obj, field) => {
                let o = self.render_expr(obj);
                format!("{o}.{}", to_snake_case(field))
            }

            ExprKind::BinOp(op, l, r) => {
                // HbValue is not Copy; clone Ident operands so the binding stays valid
                // after the operator consumes the value (avoids "use of moved value" errors).
                let lv = if matches!(l.kind, ExprKind::Ident(_)) {
                    format!("{}.clone()", self.render_expr(l))
                } else {
                    self.render_expr(l)
                };
                let rv = if matches!(r.kind, ExprKind::Ident(_)) {
                    format!("{}.clone()", self.render_expr(r))
                } else {
                    self.render_expr(r)
                };
                let op_str = match op {
                    BinOp::Add      => "+",
                    BinOp::Sub      => "-",
                    BinOp::Mul      => "*",
                    BinOp::Div      => "/",
                    BinOp::Mod      => "%",
                    BinOp::Pow      => ".pow_hb",
                    BinOp::Eq | BinOp::StrictEq => "==",
                    BinOp::NotEq    => "!=",
                    BinOp::Lt       => "<",
                    BinOp::Lte      => "<=",
                    BinOp::Gt       => ">",
                    BinOp::Gte      => ">=",
                    BinOp::And      => "&&",
                    BinOp::Or       => "||",
                    BinOp::Concat   => "+", // string concat handled by HbValue Display
                    BinOp::InStr    => "/* $ */",
                };
                if op == &BinOp::Pow {
                    format!("{lv}.pow_hb({rv})")
                } else if op == &BinOp::InStr {
                    format!("hb_instr({lv}, {rv})")
                } else {
                    format!("({lv} {op_str} {rv})")
                }
            }

            ExprKind::UnOp(op, e) => {
                let ev = self.render_expr(e);
                match op {
                    UnOp::Neg => format!("(-{ev})"),
                    UnOp::Not => format!("(!{ev})"),
                }
            }

            ExprKind::Call(c) => self.render_call(c),

            ExprKind::Iif(cond, then, else_) => {
                let c = self.render_expr(cond);
                let t = self.render_expr(then);
                let e = self.render_expr(else_);
                format!("(if {c} {{ {t} }} else {{ {e} }})")
            }
        }
    }

    // -----------------------------------------------------------------------
    // Function/method call rendering
    // -----------------------------------------------------------------------

    fn render_call(&self, call: &CallExpr) -> String {
        let args: Vec<String> = call.args.iter().map(|a| self.render_expr(a)).collect();

        // Well-known Harbour built-ins → idiomatic Rust mappings
        match call.callee.as_str() {
            "AADD" => {
                // AAdd(arr, val) → arr.hb_aadd(val)
                if args.len() == 2 {
                    return format!("{}.hb_aadd({})", args[0], args[1]);
                }
            }
            "LEN" => {
                if args.len() == 1 {
                    return format!("{}.hb_len()", args[0]);
                }
            }
            "ASIZE" => {
                if args.len() == 2 {
                    return format!("{}.hb_asize({})", args[0], args[1]);
                }
            }
            "QOUT" | "?" => {
                let val = args.first().cloned().unwrap_or_else(|| "\"\"".into());
                return format!("println!(\"{{}}\", {val})");
            }
            "ALLTRIM" | "LTRIM" | "RTRIM" => {
                if args.len() == 1 {
                    let method = match call.callee.as_str() {
                        "ALLTRIM" => "trim()",
                        "LTRIM"   => "trim_start()",
                        _         => "trim_end()",
                    };
                    return format!("{}.hb_str_op(\"|{method}|\")", args[0]);
                }
            }
            "STR" => {
                // STR(n [,len [,dec]]) — pad to 3 args since hb_str always requires all three
                if !args.is_empty() {
                    let mut a = args.clone();
                    while a.len() < 3 { a.push("HbValue::Nil".into()); }
                    return format!("hb_str({}, {}, {})", a[0], a[1], a[2]);
                }
            }
            "VAL" => {
                if args.len() == 1 {
                    return format!("hb_val({})", args[0]);
                }
            }
            "SUBSTR" => {
                return format!("hb_substr({})", args.join(", "));
            }
            "AT" => {
                if args.len() == 2 {
                    return format!("hb_at({}, {})", args[0], args[1]);
                }
            }
            _ => {}
        }

        // Generic call
        let fname = to_snake_case(&call.callee.to_ascii_lowercase());
        format!("{fname}({})", args.join(", "))
    }
}

// ---------------------------------------------------------------------------
// Public convenience
// ---------------------------------------------------------------------------

pub fn generate(program: &Program) -> String {
    Codegen::new().generate(program)
}

/// Gera o par `(<stem>.rs, <stem>_module.rs)` para o sistema Dual-File.
///
/// * `stem` — nome base do PRG sem extensão (ex: `"calc"` para `calc.prg`).
pub fn generate_dual(program: &Program, stem: &str) -> (String, String) {
    Codegen::new().generate_with_module(program, stem)
}

// ---------------------------------------------------------------------------
// Helpers livres para @..GET — sem acesso a `self`
// ---------------------------------------------------------------------------

/// Busca o texto do `@..SAY` que está na mesma linha que o `@..GET` dado.
/// Fallback: nome da variável.
fn find_say_label(get: &AtGetStmt, says: &[&AtSayStmt]) -> String {
    if let ExprKind::Integer(get_row) = &get.row.kind {
        for say in says {
            if let ExprKind::Integer(say_row) = &say.row.kind {
                if say_row == get_row {
                    if let ExprKind::String(s) = &say.expr.kind {
                        return s.clone();
                    }
                }
            }
        }
    }
    get.var.clone()
}

/// Gera o código de construção do widget a partir da PICTURE e do prefixo húngaro da variável.
fn render_widget_ctor(get: &AtGetStmt, label: &str) -> String {
    let label_esc = label.replace('"', "\\\"");
    let first = get.var.to_ascii_uppercase().chars().next().unwrap_or('C');

    match get.picture.as_deref() {
        Some(pic) if pic.starts_with("@!") => {
            let rest = pic[2..].trim();
            let width = if rest.is_empty() { 30 } else { rest.len().max(10) };
            format!("CharInput::new(\"{label_esc}\", {width}).with_picture(HbPicture::UpperCase)")
        }
        Some(pic) if pic.starts_with("@K") => {
            let rest = pic[2..].trim();
            let width = if rest.is_empty() { 30 } else { rest.len().max(10) };
            format!("CharInput::new(\"{label_esc}\", {width}).with_picture(HbPicture::KillOnFirst)")
        }
        Some(pic) if pic == "L" => {
            format!("LogicalToggle::new(\"{label_esc}\", false)")
        }
        Some(pic) if pic == "D" || pic.contains('/') => {
            format!("DateInput::new(\"{label_esc}\")")
        }
        Some(pic) if !pic.is_empty() && pic.chars().all(|c| c == '9' || c == '.') => {
            let decimals = pic.rfind('.').map(|i| pic.len() - i - 1).unwrap_or(0);
            let width = pic.len();
            format!("NumericInput::new(\"{label_esc}\", {width}, {decimals})")
        }
        Some(pic) => {
            let width = pic.len().max(10);
            format!("CharInput::new(\"{label_esc}\", {width})")
        }
        None => match first {
            'N' | 'F' => format!("NumericInput::new(\"{label_esc}\", 10, 2)"),
            'L'       => format!("LogicalToggle::new(\"{label_esc}\", false)"),
            'D'       => format!("DateInput::new(\"{label_esc}\")"),
            _         => format!("CharInput::new(\"{label_esc}\", 30)"),
        },
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::{normalize, tokenize};
    use crate::parser::parse;

    fn gen(src: &str) -> String {
        let norm = normalize(src);
        let toks: Vec<_> = tokenize(&norm).into_iter().filter_map(|(t, _)| t.ok()).collect();
        let prog = parse(toks).expect("parse failed");
        generate(&prog)
    }

    #[test]
    fn test_aadd_codegen() {
        // aTeste → to_snake_case → "ateste" (all-caps after normalize, no boundary)
        let src = "PROCEDURE Main()\nLOCAL aTeste := {}\nAAdd( aTeste, 1 )\nRETURN";
        let out = gen(src);
        assert!(out.contains("hb_aadd(HbValue::Integer(1))"), "got:\n{out}");
    }

    #[test]
    fn test_for_loop_codegen() {
        let src = "PROCEDURE Main()\nFOR i := 1 TO 10\nNEXT\nRETURN";
        let out = gen(src);
        assert!(out.contains("hb_range("), "got:\n{out}");
    }

    #[test]
    fn test_if_codegen() {
        let src = "PROCEDURE Main()\nLOCAL x := 1\nIF x == 1\nRETURN\nENDIF\nRETURN";
        let out = gen(src);
        assert!(out.contains("if (x == HbValue::Integer(1))"), "got:\n{out}");
    }

    #[test]
    fn test_func_returns_hbvalue() {
        let src = "FUNCTION Add( a, b )\nRETURN a + b";
        let out = gen(src);
        assert!(out.contains("-> HbValue"), "got:\n{out}");
        assert!(out.contains("return (a + b)"), "got:\n{out}");
    }

    #[test]
    fn test_len_mapping() {
        let src = "PROCEDURE Main()\nLOCAL a := {}\nLOCAL n := LEN(a)\nRETURN";
        let out = gen(src);
        assert!(out.contains("a.hb_len()"), "got:\n{out}");
    }

    #[test]
    fn test_public_decl_uses_store() {
        let src = "PROCEDURE Main()\nPUBLIC nEmpresa\nRETURN";
        let out = gen(src);
        assert!(out.contains("public_store().write().unwrap().set(\"NEMPRESA\", HbValue::Nil)"), "got:\n{out}");
    }

    #[test]
    fn test_public_decl_with_init() {
        let src = "PROCEDURE Main()\nPUBLIC lRecados := .T.\nRETURN";
        let out = gen(src);
        assert!(out.contains("public_store().write().unwrap().set(\"LRECADOS\", HbValue::Logical(true))"), "got:\n{out}");
    }

    #[test]
    fn test_public_assign_routes_to_store() {
        let src = "PROCEDURE Main()\nPUBLIC nEmpresa\nnEmpresa := 42\nRETURN";
        let out = gen(src);
        assert!(out.contains("public_store().write().unwrap().set(\"NEMPRESA\", HbValue::Integer(42))"), "got:\n{out}");
    }

    #[test]
    fn test_public_read_uses_store() {
        let src = "PROCEDURE Main()\nPUBLIC nEmpresa\n? nEmpresa\nRETURN";
        let out = gen(src);
        assert!(out.contains("public_store().read().unwrap().get(\"NEMPRESA\")"), "got:\n{out}");
    }

    #[test]
    fn test_top_level_memvar_skipped() {
        // MEMVAR no topo do arquivo não deve causar parse error
        let src = "memvar cor01, cor02\nPROCEDURE Main()\nRETURN";
        let out = gen(src);
        assert!(out.contains("fn main()"), "got:\n{out}");
    }

    #[test]
    fn test_at_say_get_read_emits_appstate() {
        let src = r#"
PROCEDURE Main()
LOCAL cNome := "João"
LOCAL nValor := 0
@ 5, 10 SAY "Nome:"
@ 5, 20 GET cNome PICTURE "@!"
@ 6, 10 SAY "Valor:"
@ 6, 20 GET nValor PICTURE "999"
READ
RETURN
"#;
        let out = gen(src);
        // Deve emitir o bloco scoped com AppState
        assert!(out.contains("AppState::new(__fields).run()"), "got:\n{out}");
        // Labels inferidos do SAY na mesma linha
        assert!(out.contains("CharInput::new(\"Nome:\","), "got:\n{out}");
        assert!(out.contains("NumericInput::new(\"Valor:\","), "got:\n{out}");
        // Atribuição de volta às variáveis (to_snake_case: CNOME → cnome)
        assert!(out.contains("cnome = __vals[0].clone()"), "got:\n{out}");
        assert!(out.contains("nvalor = __vals[1].clone()"), "got:\n{out}");
        // Importação local de swed_ui
        assert!(out.contains("use swed_ui::"), "got:\n{out}");
    }

    #[test]
    fn test_at_say_without_read_emits_println() {
        let src = "PROCEDURE Main()\n@ 1, 1 SAY \"Hello\"\nRETURN";
        let out = gen(src);
        assert!(out.contains("println!"), "got:\n{out}");
        assert!(out.contains("Hello"), "got:\n{out}");
    }

    // ── Dual-File Codegen ────────────────────────────────────────────────────

    fn gen_dual(src: &str, stem: &str) -> (String, String) {
        let norm = normalize(src);
        let toks: Vec<_> = tokenize(&norm).into_iter().filter_map(|(t, _)| t.ok()).collect();
        let prog = parse(toks).expect("parse failed");
        generate_dual(&prog, stem)
    }

    #[test]
    fn test_dual_main_uses_module_star() {
        let src = "PROCEDURE Main()\nLOCAL x := 1\nRETURN";
        let (main_rs, _) = gen_dual(src, "myprog");
        assert!(
            main_rs.contains("use crate::myprog_module::*;"),
            "main.rs deve usar o módulo gerado:\n{main_rs}"
        );
        assert!(
            !main_rs.contains("use swed_rt::"),
            "main.rs não deve ter imports diretos de swed_rt:\n{main_rs}"
        );
    }

    #[test]
    fn test_dual_module_always_has_hbvalue_and_store() {
        let src = "PROCEDURE Main()\nRETURN";
        let (_, module_rs) = gen_dual(src, "empty");
        assert!(module_rs.contains("pub use swed_rt::{HbValue, HbArray};"), "got:\n{module_rs}");
        assert!(module_rs.contains("pub use swed_rt::publics_var::public_store;"), "got:\n{module_rs}");
        assert!(module_rs.contains("pub use swed_db::{field_get, field_set};"), "got:\n{module_rs}");
    }

    #[test]
    fn test_dual_module_detects_hb_range_from_for() {
        let src = "PROCEDURE Main()\nFOR i := 1 TO 10\nNEXT\nRETURN";
        let (_, module_rs) = gen_dual(src, "loop_test");
        assert!(
            module_rs.contains("hb_range"),
            "module.rs deve re-exportar hb_range quando há FOR:\n{module_rs}"
        );
    }

    #[test]
    fn test_dual_module_detects_hb_str_from_str_call() {
        let src = "PROCEDURE Main()\nLOCAL c := STR(42, 5, 0)\nRETURN";
        let (_, module_rs) = gen_dual(src, "str_test");
        assert!(
            module_rs.contains("hb_str"),
            "module.rs deve re-exportar hb_str quando há STR():\n{module_rs}"
        );
    }

    #[test]
    fn test_dual_module_detects_hb_instr_from_instr_op() {
        // O operador $ do Harbour vira hb_instr no codegen
        let src = "PROCEDURE Main()\nLOCAL l := \"lo\" $ \"Hello\"\nRETURN";
        let (_, module_rs) = gen_dual(src, "instr_test");
        assert!(
            module_rs.contains("hb_instr"),
            "module.rs deve re-exportar hb_instr quando há operador $:\n{module_rs}"
        );
    }

    #[test]
    fn test_dual_module_stem_in_header() {
        let src = "PROCEDURE Main()\nRETURN";
        let (_, module_rs) = gen_dual(src, "minha_rotina");
        assert!(
            module_rs.contains("minha_rotina_module.rs"),
            "cabeçalho do module.rs deve conter o stem:\n{module_rs}"
        );
    }

    #[test]
    fn test_widget_picture_numeric() {
        let src = "PROCEDURE Main()\nLOCAL nPreco := 0\n@ 1,1 SAY \"Preco:\"\n@ 1,10 GET nPreco PICTURE \"9999.99\"\nREAD\nRETURN";
        let out = gen(src);
        assert!(out.contains("NumericInput::new(\"Preco:\", 7, 2)"), "got:\n{out}");
    }

    #[test]
    fn test_widget_picture_logical() {
        let src = "PROCEDURE Main()\nLOCAL lAtivo := .T.\n@ 1,1 SAY \"Ativo:\"\n@ 1,10 GET lAtivo PICTURE \"L\"\nREAD\nRETURN";
        let out = gen(src);
        assert!(out.contains("LogicalToggle::new(\"Ativo:\", false)"), "got:\n{out}");
    }

    #[test]
    fn test_widget_no_picture_hungarian() {
        // Sem PICTURE — infere widget pelo prefixo húngaro da variável
        let src = "PROCEDURE Main()\nLOCAL dNasc\n@ 1,1 SAY \"Nasc:\"\n@ 1,10 GET dNasc\nREAD\nRETURN";
        let out = gen(src);
        assert!(out.contains("DateInput::new(\"Nasc:\")"), "got:\n{out}");
    }
}
