// swed/src/codegen.rs
// Code Generator: ast::Program → Rust source (String)
//
// Mapping strategy (Harbour → Rust):
//   PROCEDURE p()       →  fn p()  (returns ())
//   FUNCTION  f()       →  fn f() -> HbValue
//   LOCAL x := v        →  let mut x = v;
//   STATIC x := v       →  static X: Mutex<HbValue> = ...  (via OnceCell helper)
//   DO WHILE cond       →  while cond { ... }
//   FOR i := s TO e     →  for i in (s..=e)   (step-1 shortcut)
//   FOR i := s TO e STEP n →  { let mut i=s; while i<=e { ...; i+=n; } }
//   IF/ELSEIF/ELSE      →  if / else if / else
//   AAdd(a, v)          →  a.hb_aadd(v)
//   LEN(x)              →  x.len()
//   ?  expr             →  println!("{}", expr)
//   NIL                 →  HbValue::Nil
//   .T. / .F.           →  HbValue::Logical(true/false)
//   [string]            →  HbValue::String("string".into())
//   { e1, e2 }          →  hb_array![ e1, e2 ]   (macro defined in preamble)

use std::collections::HashSet;
use crate::ast::*;
use crate::scope::to_snake_case;

// ---------------------------------------------------------------------------
// Codegen context
// ---------------------------------------------------------------------------

pub struct Codegen {
    indent: usize,
    out: String,
    /// PUBLIC names declared in the current procedure/function (UPPERCASE keys).
    pub_names: HashSet<String>,
    /// MEMVAR/PRIVATE names declared in the current procedure/function (UPPERCASE keys).
    memvar_names: HashSet<String>,
    /// FIELD names declared in the current procedure/function (UPPERCASE keys).
    /// Access emits field_get()/field_set() from swed_db.
    field_names: HashSet<String>,
}

impl Codegen {
    pub fn new() -> Self {
        Codegen {
            indent: 0,
            out: String::new(),
            pub_names: HashSet::new(),
            memvar_names: HashSet::new(),
            field_names: HashSet::new(),
        }
    }

    fn reset_var_scope(&mut self) {
        self.pub_names.clear();
        self.memvar_names.clear();
        self.field_names.clear();
    }

    fn is_public(&self, name: &str) -> bool {
        self.pub_names.contains(&name.to_ascii_uppercase())
    }

    fn is_memvar(&self, name: &str) -> bool {
        self.memvar_names.contains(&name.to_ascii_uppercase())
    }

    fn is_field(&self, name: &str) -> bool {
        self.field_names.contains(&name.to_ascii_uppercase())
    }

    // ── Output helpers ───────────────────────────────────────────────────

    fn line(&mut self, s: &str) {
        let pad = "    ".repeat(self.indent);
        self.out.push_str(&pad);
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) {
        self.out.push('\n');
    }

    fn push(&mut self, s: &str) {
        self.out.push_str(s);
    }

    fn indent(&mut self)   { self.indent += 1; }
    fn dedent(&mut self)   { if self.indent > 0 { self.indent -= 1; } }

    // -----------------------------------------------------------------------
    // Entry point
    // -----------------------------------------------------------------------

    pub fn generate(&mut self, program: &Program) -> String {
        self.emit_preamble();

        for unit in &program.units {
            self.blank();
            match unit {
                TopLevel::Procedure(p) => self.emit_proc(p),
                TopLevel::Function(f)  => self.emit_func(f),
                TopLevel::Class(c)     => self.emit_class(c),
            }
        }
        self.out.clone()
    }

    /// Gera dois arquivos: `(main_src, module_src)`.
    /// Por ora o module_src é vazio — o preamble já inclui todos os imports necessários.
    pub fn generate_with_module(&mut self, program: &Program, _stem: &str) -> (String, String) {
        (self.generate(program), String::new())
    }

    // -----------------------------------------------------------------------
    // Preamble: use statements + HbValue/HbArray re-exports + macros
    // -----------------------------------------------------------------------

    fn emit_preamble(&mut self) {
        self.line("// Generated by SWed (Shipwrecked) — do not edit manually.");
        self.line("#![allow(non_snake_case, unused_mut, unused_variables, unused_imports)]");
        self.blank();
        self.line("use swed_rt::{HbValue, HbArray};");
        self.line("use swed_rt::{pub_declare, pub_get, pub_set, memvar_assign, memvar_get}; ");
        self.blank();
        // Convenience macro for array literals  { 1, 2, 3 } → hb_array![...]
        self.line("macro_rules! hb_array {");
        self.indent();
        self.line("( $($e:expr),* $(,)? ) => {{");
        self.indent();
        self.line("let mut __a = HbArray::new();");
        self.line("$( __a.hb_aadd($e); )*");
        self.line("__a");
        self.dedent();
        self.line("}};");
        self.dedent();
        self.line("}");
    }

    // -----------------------------------------------------------------------
    // Procedure → fn name() { ... }
    // -----------------------------------------------------------------------

    fn emit_proc(&mut self, p: &ProcDef) {
        self.reset_var_scope();
        self.collect_field_names(&p.body);
        let fname = to_snake_case(&p.name);
        if p.name.to_ascii_uppercase() == "MAIN" {
            // Rust entry point: fn main() never takes parameters.
            // Harbour Main params come from the OS command line — bind them here.
            self.line("fn main() {");
            self.indent();
            if !p.params.is_empty() {
                self.line("let mut __args: Vec<HbValue> = std::env::args().skip(1)");
                self.line("    .map(|s| HbValue::String(s)).collect();");
                for (i, param) in p.params.iter().enumerate() {
                    let pname = to_snake_case(&param.name);
                    self.line(&format!(
                        "let mut {pname} = __args.get({i}).cloned().unwrap_or(HbValue::Nil);"
                    ));
                }
            }
        } else {
            let params = self.render_params(&p.params);
            self.line(&format!("fn {fname}({params}) {{"));
            self.indent();
        }
        if !self.field_names.is_empty() {
            self.line("use swed_db::{field_get, field_set};");
        }
        self.emit_stmts(&p.body);
        self.dedent();
        self.line("}");
    }

    // -----------------------------------------------------------------------
    // Function → fn name(...) -> HbValue { ... }
    // -----------------------------------------------------------------------

    fn emit_func(&mut self, f: &FuncDef) {
        self.reset_var_scope();
        self.collect_field_names(&f.body);
        let fname = to_snake_case(&f.name);

        // FUNCTION Main is the Harbour entry point; Rust main() cannot return HbValue.
        // Wrap the body in a closure so `return expr` stays valid Rust, then discard.
        if f.name.to_ascii_uppercase() == "MAIN" {
            self.line("fn main() {");
            self.indent();
            if !self.field_names.is_empty() {
                self.line("use swed_db::{field_get, field_set};");
            }
            self.line("let _: HbValue = (|| {");
            self.indent();
            self.emit_stmts(&f.body);
            self.line("HbValue::Nil");
            self.dedent();
            self.line("})();");
            self.dedent();
            self.line("}");
            return;
        }

        let params = self.render_params(&f.params);
        self.line(&format!("fn {fname}({params}) -> HbValue {{"));
        self.indent();
        if !self.field_names.is_empty() {
            self.line("use swed_db::{field_get, field_set};");
        }
        self.emit_stmts(&f.body);
        // Ensure there is always a fallback return
        self.line("HbValue::Nil");
        self.dedent();
        self.line("}");
    }

    fn render_params(&self, params: &[Param]) -> String {
        params
            .iter()
            .map(|p| format!("mut {}: HbValue", to_snake_case(&p.name)))
            .collect::<Vec<_>>()
            .join(", ")
    }

    // -----------------------------------------------------------------------
    // Pré-scan: coleta nomes FIELD de um corpo — FIELD tem prioridade sobre
    // PUBLIC/MEMVAR mas abaixo de LOCAL/STATIC.
    // -----------------------------------------------------------------------

    fn collect_field_names(&mut self, body: &[Stmt]) {
        self.field_names.clear();
        self.collect_fields_recursive(body);
    }

    fn collect_fields_recursive(&mut self, stmts: &[Stmt]) {
        for s in stmts {
            match &s.kind {
                StmtKind::FieldDecl { names, .. } => {
                    for n in names {
                        self.field_names.insert(n.to_ascii_uppercase());
                    }
                }
                StmtKind::If(i) => {
                    self.collect_fields_recursive(&i.then_body);
                    for (_, b) in &i.elseif_branches { self.collect_fields_recursive(b); }
                    if let Some(b) = &i.else_body { self.collect_fields_recursive(b); }
                }
                StmtKind::DoWhile(w) => self.collect_fields_recursive(&w.body),
                StmtKind::For(f)     => self.collect_fields_recursive(&f.body),
                _ => {}
            }
        }
    }

    // -----------------------------------------------------------------------
    // Class → struct + impl block (skeleton)
    // -----------------------------------------------------------------------

    fn emit_class(&mut self, c: &ClassDef) {
        let sname = &c.name;
        self.line(&format!("// CLASS {sname}"));
        self.line(&format!("struct {sname} {{"));
        self.indent();
        for d in &c.data {
            let field = to_snake_case(&d.name);
            self.line(&format!("{field}: HbValue,"));
        }
        self.dedent();
        self.line("}");
        self.blank();
        self.line(&format!("impl {sname} {{"));
        self.indent();
        // Default constructor
        self.line("fn new() -> Self {");
        self.indent();
        self.line(&format!("{sname} {{"));
        self.indent();
        for d in &c.data {
            let field = to_snake_case(&d.name);
            self.line(&format!("{field}: HbValue::Nil,"));
        }
        self.dedent();
        self.line("}");
        self.dedent();
        self.line("}");
        // Methods
        for m in &c.methods {
            self.blank();
            let params = self.render_params(&m.params);
            let sep = if params.is_empty() { "".to_string() } else { format!(", {params}") };
            let mname = to_snake_case(&m.name);
            self.line(&format!("fn {mname}(&mut self{sep}) -> HbValue {{"));
            self.indent();
            self.emit_stmts(&m.body);
            self.line("HbValue::Nil");
            self.dedent();
            self.line("}");
        }
        self.dedent();
        self.line("}");
    }

    // -----------------------------------------------------------------------
    // Statements
    // -----------------------------------------------------------------------

    fn emit_stmts(&mut self, stmts: &[Stmt]) {
        let mut i = 0;
        while i < stmts.len() {
            match &stmts[i].kind {
                StmtKind::AtSay(_) | StmtKind::AtGet(_) => {
                    // Encontra o READ que fecha este bloco (inclusive)
                    let maybe_read = stmts[i..]
                        .iter()
                        .position(|s| matches!(s.kind, StmtKind::Read));
                    if let Some(rel) = maybe_read {
                        let end = i + rel + 1;
                        self.emit_read_block(&stmts[i..end]);
                        i = end;
                    } else {
                        // SAY sem READ → println simples; GET sem READ → ignorado
                        if let StmtKind::AtSay(say) = &stmts[i].kind {
                            let val = self.render_expr(&say.expr);
                            let pad = "    ".repeat(self.indent);
                            self.out.push_str(&format!("{pad}println!(\"{{}}\", {val});\n"));
                        }
                        i += 1;
                    }
                }
                StmtKind::Read => {
                    // READ sem @..GET precedente — ignorado
                    i += 1;
                }
                _ => {
                    self.emit_stmt(&stmts[i]);
                    i += 1;
                }
            }
        }
    }

    /// Emite um bloco scoped com AppState para o grupo SAY/GET...READ.
    fn emit_read_block(&mut self, stmts: &[Stmt]) {
        // Separa SAYs e GETs (preserva ordem dos GETs para o índice de retorno)
        let mut says: Vec<&AtSayStmt> = Vec::new();
        let mut gets: Vec<&AtGetStmt> = Vec::new();
        for s in stmts {
            match &s.kind {
                StmtKind::AtSay(say) => says.push(say),
                StmtKind::AtGet(get) => gets.push(get),
                _ => {}
            }
        }

        // Pré-computa labels e construtores de widget antes de mutar self.out
        let widgets: Vec<(String, String)> = gets
            .iter()
            .map(|get| {
                let label = find_say_label(get, &says);
                let ctor  = render_widget_ctor(get, &label);
                (to_snake_case(&get.var), ctor)
            })
            .collect();

        self.line("{");
        self.indent();

        // Importa swed_ui apenas no escopo do bloco — sem poluir o namespace global
        self.line("use swed_ui::{AppState, ReadResult, GetElement,");
        self.line("    CharInput, NumericInput, DateInput, LogicalToggle};");
        self.line("use swed_ui::widgets::char_input::Picture as HbPicture;");
        self.line("let mut __fields: Vec<Box<dyn GetElement>> = Vec::new();");

        for (snake, ctor) in &widgets {
            self.line("{");
            self.indent();
            self.line(&format!("let mut __f: Box<dyn GetElement> = Box::new({ctor});"));
            self.line(&format!("__f.set_value({snake}.clone());"));
            self.line("__fields.push(__f);");
            self.dedent();
            self.line("}");
        }

        self.line("match AppState::new(__fields).run() {");
        self.indent();
        self.line("Ok(ReadResult::Confirmed(__vals)) => {");
        self.indent();
        for (idx, (snake, _)) in widgets.iter().enumerate() {
            self.line(&format!("{snake} = __vals[{idx}].clone();"));
        }
        self.dedent();
        self.line("}");
        self.line("_ => {}");
        self.dedent();
        self.line("}");

        self.dedent();
        self.line("}");
    }

    fn emit_stmt(&mut self, stmt: &Stmt) {
        let pad = "    ".repeat(self.indent);
        match &stmt.kind {

            StmtKind::VarDecl(d) => {
                for v in &d.vars {
                    let name = to_snake_case(&v.name);
                    let init = v.init.as_ref()
                        .map(|e| self.render_expr(e))
                        .unwrap_or_else(|| "HbValue::Nil".into());
                    self.out.push_str(&format!("{pad}let mut {name} = {init};\n"));
                }
            }

            StmtKind::StaticDecl(d) => {
                // STATIC → thread_local! with RefCell
                for v in &d.vars {
                    let name = to_snake_case(&v.name).to_ascii_uppercase();
                    let init = v.init.as_ref()
                        .map(|e| self.render_expr(e))
                        .unwrap_or_else(|| "HbValue::Nil".into());
                    self.out.push_str(&format!(
                        "{pad}thread_local! {{ static {name}: std::cell::RefCell<HbValue> \
                         = std::cell::RefCell::new({init}); }}\n"
                    ));
                }
            }

            StmtKind::PublicDecl(d) => {
                for v in &d.vars {
                    let key = v.name.to_ascii_uppercase();
                    let init = v.init.as_ref()
                        .map(|e| self.render_expr(e))
                        .unwrap_or_else(|| "HbValue::Nil".into());
                    self.pub_names.insert(key.clone());
                    self.out.push_str(&format!("{pad}pub_declare(\"{key}\", {init});\n"));
                }
            }

            StmtKind::MemvarDecl(names) => {
                for n in names {
                    let key = n.to_ascii_uppercase();
                    self.memvar_names.insert(key.clone());
                    self.out.push_str(&format!("{pad}memvar_assign(\"{key}\", HbValue::Nil);\n"));
                }
            }

            StmtKind::Assign(a) => {
                let value = self.render_expr(&a.value);
                match &a.target.kind {
                    // Priority: FIELD > PUBLIC > MEMVAR > LOCAL
                    ExprKind::Ident(name) if self.is_field(name) => {
                        let key = name.to_ascii_uppercase();
                        self.out.push_str(&format!("{pad}field_set(\"{key}\", {value});\n"));
                    }
                    ExprKind::Ident(name) if self.is_public(name) => {
                        let key = name.to_ascii_uppercase();
                        self.out.push_str(&format!("{pad}pub_set(\"{key}\", {value});\n"));
                    }
                    ExprKind::Ident(name) if self.is_memvar(name) => {
                        let key = name.to_ascii_uppercase();
                        self.out.push_str(&format!("{pad}memvar_assign(\"{key}\", {value});\n"));
                    }
                    _ => {
                        let target = self.render_expr(&a.target);
                        self.out.push_str(&format!("{pad}{target} = {value};\n"));
                    }
                }
            }

            StmtKind::Store(s) => {
                let value = self.render_expr(&s.value);
                for var in &s.vars {
                    if self.is_field(var) {
                        let key = var.to_ascii_uppercase();
                        self.out.push_str(&format!("{pad}field_set(\"{key}\", {value}.clone());\n"));
                    } else if self.is_public(var) {
                        let key = var.to_ascii_uppercase();
                        self.out.push_str(&format!("{pad}pub_set(\"{key}\", {value}.clone());\n"));
                    } else if self.is_memvar(var) {
                        let key = var.to_ascii_uppercase();
                        self.out.push_str(&format!("{pad}memvar_assign(\"{key}\", {value}.clone());\n"));
                    } else {
                        let vname = to_snake_case(var);
                        self.out.push_str(&format!("{pad}{vname} = {value}.clone();\n"));
                    }
                }
            }

            StmtKind::Exit => {
                self.out.push_str(&format!("{pad}break;\n"));
            }

            StmtKind::Loop => {
                self.out.push_str(&format!("{pad}continue;\n"));
            }

            StmtKind::Cls => {
                self.out.push_str(&format!("{pad}print!(\"\\x1B[2J\\x1B[H\");\n")); // ANSI clear screen
            }

            StmtKind::Call(c) => {
                let call = self.render_call(c);
                self.out.push_str(&format!("{pad}{call};\n"));
            }

            StmtKind::Print(e) => {
                let val = self.render_expr(e);
                self.out.push_str(&format!("{pad}println!(\"{{}}\", {val});\n"));
            }

            StmtKind::If(i) => {
                let cond = self.render_expr(&i.condition);
                self.out.push_str(&format!("{pad}if {cond} {{\n"));
                self.indent();
                self.emit_stmts(&i.then_body);
                self.dedent();
                for (ec, eb) in &i.elseif_branches {
                    let ec_r = self.render_expr(ec);
                    self.out.push_str(&format!("{pad}}} else if {ec_r} {{\n"));
                    self.indent();
                    self.emit_stmts(eb);
                    self.dedent();
                }
                if let Some(eb) = &i.else_body {
                    self.out.push_str(&format!("{pad}}} else {{\n"));
                    self.indent();
                    self.emit_stmts(eb);
                    self.dedent();
                }
                self.out.push_str(&format!("{pad}}}\n"));
            }

            StmtKind::DoWhile(w) => {
                let cond = self.render_expr(&w.condition);
                self.out.push_str(&format!("{pad}while {cond} {{\n"));
                self.indent();
                self.emit_stmts(&w.body);
                self.dedent();
                self.out.push_str(&format!("{pad}}}\n"));
            }

            StmtKind::For(f) => {
                let start = self.render_expr(&f.start);
                let end   = self.render_expr(&f.end);
                let var   = to_snake_case(&f.var);

                if f.step.is_none() {
                    // Simple STEP 1 case → idiomatic Rust range
                    self.out.push_str(&format!(
                        "{pad}for {var} in hb_range({start}, {end}, 1) {{\n"
                    ));
                } else {
                    let step = self.render_expr(f.step.as_ref().unwrap());
                    self.out.push_str(&format!(
                        "{pad}for {var} in hb_range({start}, {end}, {step}) {{\n"
                    ));
                }
                self.indent();
                self.emit_stmts(&f.body);
                self.dedent();
                self.out.push_str(&format!("{pad}}}\n"));
            }

            StmtKind::Return(e) => {
                match e {
                    Some(expr) => {
                        let val = self.render_expr(expr);
                        self.out.push_str(&format!("{pad}return {val};\n"));
                    }
                    None => self.out.push_str(&format!("{pad}return;\n")),
                }
            }

            // FIELD é mapeamento para WorkArea; sem alocação de variável local.
            StmtKind::FieldDecl { .. } => {}

            // Tratados em lote por emit_stmts → emit_read_block
            StmtKind::AtSay(_) | StmtKind::AtGet(_) | StmtKind::Read => {}
        }
    }

    // -----------------------------------------------------------------------
    // Expressions → &str
    // -----------------------------------------------------------------------

    fn render_expr(&self, expr: &Expr) -> String {
        match &expr.kind {
            ExprKind::Nil               => "HbValue::Nil".into(),
            ExprKind::Bool(b)           => format!("HbValue::Logical({b})"),
            ExprKind::Integer(n)        => format!("HbValue::Integer({n})"),
            ExprKind::Float(f)          => format!("HbValue::Float({f})"),
            ExprKind::String(s)         => format!("HbValue::String(\"{}\".into())", s.replace('"', "\\\"")),
            ExprKind::Ident(name) => {
                let key = name.to_ascii_uppercase();
                if self.field_names.contains(&key) {
                    format!("field_get(\"{key}\")")
                } else if self.pub_names.contains(&key) {
                    format!("pub_get(\"{key}\")")
                } else if self.memvar_names.contains(&key) {
                    format!("memvar_get(\"{key}\")")
                } else {
                    to_snake_case(name)
                }
            }
            // m->varname — sempre busca no pool PUBLIC/MEMVAR, ignora LOCAL
            ExprKind::Macro(name) => {
                let key = name.to_ascii_uppercase();
                format!("memvar_get(\"{key}\")")
            }

            ExprKind::ArrayLit(elems) => {
                let inner: Vec<String> = elems.iter().map(|e| self.render_expr(e)).collect();
                format!("hb_array![{}]", inner.join(", "))
            }

            ExprKind::Index(arr, idx) => {
                let a = self.render_expr(arr);
                let i = self.render_expr(idx);
                // HbValue is not Copy; clone so the index variable stays usable after this call
                format!("{a}.hb_get_val({i}.clone())")
            }

            ExprKind::Field(obj, field) => {
                let o = self.render_expr(obj);
                format!("{o}.{}", to_snake_case(field))
            }

            ExprKind::BinOp(op, l, r) => {
                // HbValue is not Copy; clone Ident operands so the binding stays valid
                // after the operator consumes the value (avoids "use of moved value" errors).
                let lv = if matches!(l.kind, ExprKind::Ident(_)) {
                    format!("{}.clone()", self.render_expr(l))
                } else {
                    self.render_expr(l)
                };
                let rv = if matches!(r.kind, ExprKind::Ident(_)) {
                    format!("{}.clone()", self.render_expr(r))
                } else {
                    self.render_expr(r)
                };
                let op_str = match op {
                    BinOp::Add      => "+",
                    BinOp::Sub      => "-",
                    BinOp::Mul      => "*",
                    BinOp::Div      => "/",
                    BinOp::Mod      => "%",
                    BinOp::Pow      => ".pow_hb",
                    BinOp::Eq | BinOp::StrictEq => "==",
                    BinOp::NotEq    => "!=",
                    BinOp::Lt       => "<",
                    BinOp::Lte      => "<=",
                    BinOp::Gt       => ">",
                    BinOp::Gte      => ">=",
                    BinOp::And      => "&&",
                    BinOp::Or       => "||",
                    BinOp::Concat   => "+", // string concat handled by HbValue Display
                    BinOp::InStr    => "/* $ */",
                };
                if op == &BinOp::Pow {
                    format!("{lv}.pow_hb({rv})")
                } else if op == &BinOp::InStr {
                    format!("hb_instr({lv}, {rv})")
                } else {
                    format!("({lv} {op_str} {rv})")
                }
            }

            ExprKind::UnOp(op, e) => {
                let ev = self.render_expr(e);
                match op {
                    UnOp::Neg => format!("(-{ev})"),
                    UnOp::Not => format!("(!{ev})"),
                    UnOp::PreIncrement => {
                        // ++i: incrementa e retorna o novo valor
                        format!("{{ {ev} += HbValue::Integer(1); {ev}.clone() }}")
                    }
                    UnOp::PreDecrement => {
                        // --i: decrementa e retorna o novo valor
                        format!("{{ {ev} -= HbValue::Integer(1); {ev}.clone() }}")
                    }
                    UnOp::PostIncrement => {
                        // i++: retorna o valor antigo e incrementa
                        format!("{{ let old = {ev}.clone(); {ev} += HbValue::Integer(1); old }}")
                    }
                    UnOp::PostDecrement => {
                        // i--: retorna o valor antigo e decrementa
                        format!("{{ let old = {ev}.clone(); {ev} -= HbValue::Integer(1); old }}")
                    }
                }
            }

            ExprKind::Call(c) => self.render_call(c),

            ExprKind::Iif(cond, then, else_) => {
                let c = self.render_expr(cond);
                let t = self.render_expr(then);
                let e = self.render_expr(else_);
                format!("(if {c} {{ {t} }} else {{ {e} }})")
            }
        }
    }

    // -----------------------------------------------------------------------
    // Function/method call rendering
    // -----------------------------------------------------------------------

    fn render_call(&self, call: &CallExpr) -> String {
        let args: Vec<String> = call.args.iter().map(|a| self.render_expr(a)).collect();

        // Well-known Harbour built-ins → idiomatic Rust mappings
        match call.callee.as_str() {
            // Expression used as statement (post-increment/decrement side-effects).
            // The arg is already the full expression block; emit it directly.
            "__EXPR_STMT__" => {
                if args.len() == 1 {
                    return args[0].clone();
                }
            }
            "AADD" => {
                // AAdd(arr, val) → arr.hb_aadd(val)
                if args.len() == 2 {
                    return format!("{}.hb_aadd({})", args[0], args[1]);
                }
            }
            "LEN" => {
                if args.len() == 1 {
                    return format!("{}.hb_len()", args[0]);
                }
            }
            "ASIZE" => {
                if args.len() == 2 {
                    return format!("{}.hb_asize({})", args[0], args[1]);
                }
            }
            "QOUT" | "?" => {
                let val = args.first().cloned().unwrap_or_else(|| "\"\"".into());
                return format!("println!(\"{{}}\", {val})");
            }
            "ALLTRIM" | "LTRIM" | "RTRIM" => {
                if args.len() == 1 {
                    let method = match call.callee.as_str() {
                        "ALLTRIM" => "trim()",
                        "LTRIM"   => "trim_start()",
                        _         => "trim_end()",
                    };
                    return format!("{}.hb_str_op(\"|{method}|\")", args[0]);
                }
            }
            // ── swed_nm IndexAssignNorm output ────────────────────────────
            // a[i] := v  →  a.hb_set_val(i, v)
            "HB_SET_VAL" => {
                if args.len() == 3 {
                    return format!("{}.hb_set_val({}, {})", args[0], args[1], args[2]);
                }
            }
            // a[i][j] := v  →  a.hb_set_nested(i, j, v)
            "HB_SET_NESTED" => {
                if args.len() == 4 {
                    return format!(
                        "{}.hb_set_nested({}, {}, {})",
                        args[0], args[1], args[2], args[3]
                    );
                }
            }

            "STR" => {
                // STR(n [,len [,dec]]) — pad to 3 args since hb_str always requires all three
                if !args.is_empty() {
                    let mut a = args.clone();
                    while a.len() < 3 { a.push("HbValue::Nil".into()); }
                    return format!("hb_str({}, {}, {})", a[0], a[1], a[2]);
                }
            }
            "VAL" => {
                if args.len() == 1 {
                    return format!("hb_val({})", args[0]);
                }
            }
            "SUBSTR" => {
                return format!("hb_substr({})", args.join(", "));
            }
            "AT" => {
                if args.len() == 2 {
                    return format!("hb_at({}, {})", args[0], args[1]);
                }
            }
            _ => {}
        }

        // Generic call
        let fname = to_snake_case(&call.callee.to_ascii_lowercase());
        format!("{fname}({})", args.join(", "))
    }
}

// ---------------------------------------------------------------------------
// Public convenience
// ---------------------------------------------------------------------------

pub fn generate(program: &Program) -> String {
    Codegen::new().generate(program)
}

/// Gera o par `(<stem>.rs, <stem>_module.rs)` para o sistema Dual-File.
///
/// * `stem` — nome base do PRG sem extensão (ex: `"calc"` para `calc.prg`).
pub fn generate_dual(program: &Program, stem: &str) -> (String, String) {
    Codegen::new().generate_with_module(program, stem)
}

// ---------------------------------------------------------------------------
// Helpers livres para @..GET — sem acesso a `self`
// ---------------------------------------------------------------------------

/// Busca o texto do `@..SAY` que está na mesma linha que o `@..GET` dado.
/// Fallback: nome da variável.
fn find_say_label(get: &AtGetStmt, says: &[&AtSayStmt]) -> String {
    if let ExprKind::Integer(get_row) = &get.row.kind {
        for say in says {
            if let ExprKind::Integer(say_row) = &say.row.kind {
                if say_row == get_row {
                    if let ExprKind::String(s) = &say.expr.kind {
                        return s.clone();
                    }
                }
            }
        }
    }
    get.var.clone()
}

/// Gera o código de construção do widget a partir da PICTURE e do prefixo húngaro da variável.
fn render_widget_ctor(get: &AtGetStmt, label: &str) -> String {
    let label_esc = label.replace('"', "\\\"");
    let first = get.var.to_ascii_uppercase().chars().next().unwrap_or('C');

    match get.picture.as_deref() {
        Some(pic) if pic.starts_with("@!") => {
            let rest = pic[2..].trim();
            let width = if rest.is_empty() { 30 } else { rest.len().max(10) };
            format!("CharInput::new(\"{label_esc}\", {width}).with_picture(HbPicture::UpperCase)")
        }
        Some(pic) if pic.starts_with("@K") => {
            let rest = pic[2..].trim();
            let width = if rest.is_empty() { 30 } else { rest.len().max(10) };
            format!("CharInput::new(\"{label_esc}\", {width}).with_picture(HbPicture::KillOnFirst)")
        }
        Some(pic) if pic == "L" => {
            format!("LogicalToggle::new(\"{label_esc}\", false)")
        }
        Some(pic) if pic == "D" || pic.contains('/') => {
            format!("DateInput::new(\"{label_esc}\")")
        }
        Some(pic) if !pic.is_empty() && pic.chars().all(|c| c == '9' || c == '.') => {
            let decimals = pic.rfind('.').map(|i| pic.len() - i - 1).unwrap_or(0);
            let width = pic.len();
            format!("NumericInput::new(\"{label_esc}\", {width}, {decimals})")
        }
        Some(pic) => {
            let width = pic.len().max(10);
            format!("CharInput::new(\"{label_esc}\", {width})")
        }
        None => match first {
            'N' | 'F' => format!("NumericInput::new(\"{label_esc}\", 10, 2)"),
            'L'       => format!("LogicalToggle::new(\"{label_esc}\", false)"),
            'D'       => format!("DateInput::new(\"{label_esc}\")"),
            _         => format!("CharInput::new(\"{label_esc}\", 30)"),
        },
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::{normalize, tokenize};
    use crate::parser::parse;

    fn gen(src: &str) -> String {
        let norm = normalize(src);
        let toks: Vec<_> = tokenize(&norm).into_iter().filter_map(|(t, _)| t.ok()).collect();
        let prog = parse(toks).expect("parse failed");
        generate(&prog)
    }

    #[test]
    fn test_aadd_codegen() {
        // aTeste → to_snake_case → "ateste" (all-caps after normalize, no boundary)
        let src = "PROCEDURE Main()\nLOCAL aTeste := {}\nAAdd( aTeste, 1 )\nRETURN";
        let out = gen(src);
        assert!(out.contains("hb_aadd(HbValue::Integer(1))"), "got:\n{out}");
    }

    #[test]
    fn test_for_loop_codegen() {
        let src = "PROCEDURE Main()\nFOR i := 1 TO 10\nNEXT\nRETURN";
        let out = gen(src);
        assert!(out.contains("hb_range("), "got:\n{out}");
    }

    #[test]
    fn test_if_codegen() {
        let src = "PROCEDURE Main()\nLOCAL x := 1\nIF x == 1\nRETURN\nENDIF\nRETURN";
        let out = gen(src);
        assert!(out.contains("HbValue::Integer(1))"), "got:\n{out}");
    }

    #[test]
    fn test_func_returns_hbvalue() {
        let src = "FUNCTION Add( a, b )\nRETURN a + b";
        let out = gen(src);
        assert!(out.contains("-> HbValue"), "got:\n{out}");
        assert!(out.contains("return (a") && out.contains("+ b"), "got:\n{out}");
    }

    #[test]
    fn test_len_mapping() {
        let src = "PROCEDURE Main()\nLOCAL a := {}\nLOCAL n := LEN(a)\nRETURN";
        let out = gen(src);
        assert!(out.contains("a.hb_len()"), "got:\n{out}");
    }

    #[test]
    fn test_public_decl_uses_pub_declare() {
        let src = "PROCEDURE Main()\nPUBLIC nCounter\nRETURN";
        let out = gen(src);
        assert!(out.contains("pub_declare(\"NCOUNTER\", HbValue::Nil)"), "got:\n{out}");
        assert!(!out.contains("let mut n_counter"), "PUBLIC não deve gerar let mut; got:\n{out}");
    }

    #[test]
    fn test_public_assign_uses_pub_set() {
        let src = "PROCEDURE Main()\nPUBLIC nCounter\nnCounter := 42\nRETURN";
        let out = gen(src);
        assert!(out.contains("pub_set(\"NCOUNTER\", HbValue::Integer(42))"), "got:\n{out}");
        assert!(!out.contains("n_counter = HbValue"), "PUBLIC assign não deve ser let; got:\n{out}");
    }

    #[test]
    fn test_public_read_uses_pub_get() {
        let src = "PROCEDURE Main()\nPUBLIC nCounter\n? nCounter\nRETURN";
        let out = gen(src);
        assert!(out.contains("pub_get(\"NCOUNTER\")"), "got:\n{out}");
    }

    #[test]
    fn test_memvar_decl_uses_memvar_assign() {
        let src = "PROCEDURE Main()\nMEMVAR cName\nRETURN";
        let out = gen(src);
        assert!(out.contains("memvar_assign(\"CNAME\", HbValue::Nil)"), "got:\n{out}");
        assert!(!out.contains("let mut c_name"), "MEMVAR não deve gerar let mut; got:\n{out}");
    }

    #[test]
    fn test_memvar_assign_uses_memvar_assign() {
        let src = "PROCEDURE Main()\nMEMVAR cName\ncName := \"Alice\"\nRETURN";
        let out = gen(src);
        assert!(out.contains("memvar_assign(\"CNAME\","), "got:\n{out}");
    }

    #[test]
    fn test_m_arrow_codegen() {
        // m->nCounter deve gerar memvar_get("NCOUNTER"), nunca acessar LOCAL
        let src = "PROCEDURE Main()\n? m->nCounter\nRETURN";
        let out = gen(src);
        assert!(out.contains("memvar_get(\"NCOUNTER\")"), "got:\n{out}");
    }

    #[test]
    fn test_public_scope_reset_between_procs() {
        // nCounter PUBLIC em Main não deve vazar para AnotherProc
        let src = "PROCEDURE Main()\nPUBLIC nCounter\nRETURN\nPROCEDURE AnotherProc()\n? nCounter\nRETURN";
        let out = gen(src);
        // Em AnotherProc, nCounter é desconhecido → local (to_snake_case)
        // O pub_get só aparece dentro de Main
        let main_part = out.split("fn another_proc").next().unwrap_or("");
        assert!(main_part.contains("pub_declare(\"NCOUNTER\""), "got:\n{out}");
        let other_part = out.split("fn another_proc").nth(1).unwrap_or("");
        assert!(!other_part.contains("pub_get(\"NCOUNTER\")"), "PUBLIC de Main não deve vazar; got:\n{out}");
    }

    // ── FIELD / DBF ────────────────────────────────────────────────────────────

    #[test]
    fn test_field_read_uses_field_get() {
        let src = "PROCEDURE Main()\nFIELD nSalario\n? nSalario\nRETURN";
        let out = gen(src);
        assert!(out.contains("field_get(\"NSALARIO\")"), "got:\n{out}");
        assert!(!out.contains("let mut n_salario"), "FIELD não deve gerar let mut; got:\n{out}");
    }

    #[test]
    fn test_field_assign_uses_field_set() {
        let src = "PROCEDURE Main()\nFIELD nSalario\nnSalario := 5000\nRETURN";
        let out = gen(src);
        assert!(out.contains("field_set(\"NSALARIO\", HbValue::Integer(5000))"), "got:\n{out}");
    }

    #[test]
    fn test_field_imports_swed_db() {
        let src = "PROCEDURE Main()\nFIELD cNome\nRETURN";
        let out = gen(src);
        assert!(out.contains("use swed_db::{field_get, field_set}"), "got:\n{out}");
    }

    #[test]
    fn test_no_field_no_swed_db_import() {
        let src = "PROCEDURE Main()\nLOCAL x := 1\nRETURN";
        let out = gen(src);
        assert!(!out.contains("swed_db"), "sem FIELD não deve importar swed_db; got:\n{out}");
    }

    #[test]
    fn test_field_priority_over_public() {
        // FIELD tem prioridade sobre PUBLIC quando o mesmo nome aparece nos dois escopos
        let src = "PROCEDURE Main()\nFIELD nVal\nPUBLIC nVal\n? nVal\nRETURN";
        let out = gen(src);
        assert!(out.contains("field_get(\"NVAL\")"), "FIELD deve ter prioridade; got:\n{out}");
        assert!(!out.contains("pub_get(\"NVAL\")"), "pub_get não deve aparecer; got:\n{out}");
    }

    // ── Bug-regression tests ───────────────────────────────────────────────────

    #[test]
    fn test_store_uses_snake_case() {
        // STORE 5 TO nLinha, nColuna must emit snake_case idents, not uppercase.
        let src = "PROCEDURE Main()\nLOCAL nLinha\nLOCAL nColuna\nSTORE 5 TO nLinha, nColuna\nRETURN";
        let out = gen(src);
        assert!(out.contains("nlinha = HbValue::Integer(5)"), "STORE deve usar snake_case; got:\n{out}");
        assert!(out.contains("ncoluna = HbValue::Integer(5)"), "STORE deve usar snake_case; got:\n{out}");
        assert!(!out.contains("NLINHA ="), "STORE não deve usar uppercase; got:\n{out}");
    }

    #[test]
    fn test_function_main_emits_fn_main_without_hbvalue_return() {
        // `function main()` must emit `fn main()`, not `fn main() -> HbValue`.
        let src = "function main()\nRETURN 0";
        let out = gen(src);
        assert!(out.contains("fn main() {"), "function main deve gerar fn main(); got:\n{out}");
        assert!(!out.contains("fn main() -> HbValue"), "fn main não pode ter -> HbValue; got:\n{out}");
    }

    #[test]
    fn test_post_increment_as_stmt_no_expr_stmt_call() {
        // nVar++ as statement must NOT generate `expr_stmt(...)` (undefined function).
        let src = "PROCEDURE Main()\nLOCAL nVar := 0\nnVar++\nRETURN";
        let out = gen(src);
        assert!(!out.contains("expr_stmt("), "expr_stmt não deve aparecer; got:\n{out}");
        assert!(out.contains("nvar"), "variável deve aparecer; got:\n{out}");
    }
}
