[package]
name         = "demo"
version      = "0.1.0"
edition      = "2021"
authors      = ["Sr. Barruga"]
description  = "SWed demo — Sandbox de código transpilado"

[[bin]]
name = "demo"
path = "demo.rs"

[dependencies]
# Referência direta por caminho relativo para as crates de suporte
swed_rt = { path = "/home/barruga/project/beta/shipwrecked/swed_rt" }
swed_db = { path = "/home/barruga/project/beta/shipwrecked/swed_db" }
swed_bf = { path = "/home/barruga/project/beta/shipwrecked/swed_bf" }

[workspace]
# Este bloco vazio impede que o Cargo suba para o diretório pai 
# e tente encontrar o workspace principal.