// Generated by SWed (Shipwrecked) — do not edit manually.
#![allow(non_snake_case, unused_mut, unused_variables, unused_imports)]

mod demo_module;
use crate::demo_module::*;

macro_rules! hb_array {
    ( $($e:expr),* $(,)? ) => {{
        let mut __a = HbArray::new();
        $( __a.hb_aadd($e); )*
        __a
    }};
}

fn main() {
    let mut __args: Vec<HbValue> = std::env::args().skip(1)
        .map(|s| HbValue::String(s)).collect();
    let mut nvalor = __args.get(0).cloned().unwrap_or(HbValue::Nil);
    let mut nlocal = __args.get(1).cloned().unwrap_or(HbValue::Nil);
    let mut nquantidade = __args.get(2).cloned().unwrap_or(HbValue::Nil);
    let mut errado = __args.get(3).cloned().unwrap_or(HbValue::Nil);
    let mut anomes = hb_array![];
    let mut ascores = hb_array![];
    let mut i = HbValue::Integer(0);
    let mut ntotal = HbValue::Integer(0);
    let mut amax = hb_array![HbValue::Integer(1), HbValue::Integer(10), HbValue::Integer(15)];
    let mut cnome = HbValue::String("".into());
    let mut getlist = hb_array![];
    anomes.hb_aadd(HbValue::String("Alice".into()));
    anomes.hb_aadd(HbValue::String("Bob".into()));
    anomes.hb_aadd(HbValue::String("Charlie".into()));
    anomes.hb_aadd(HbValue::String("Blink".into()));
    ascores.hb_aadd(HbValue::Integer(92));
    ascores.hb_aadd(HbValue::Integer(87));
    ascores.hb_aadd(HbValue::Integer(95));
    if (nvalor.clone() == HbValue::Integer(0)) {
        nlocal = HbValue::Integer(5);
        errado = HbValue::String("TEXT".into());
    }
    println!("{}", HbValue::String("=== Score Report ===".into()));
    println!("{}", HbValue::String("".into()));
    for i in hb_range(HbValue::Integer(1), anomes.hb_len(), HbValue::Integer(1)) {
        cnome = anomes.hb_get_val(i.clone());
        ntotal = (ntotal.clone() + ascores.hb_get_val(i.clone()));
        println!("{}", ((cnome.clone() + HbValue::String(": ".into())) + hb_str(ascores.hb_get_val(i.clone()), HbValue::Nil, HbValue::Nil)));
    }
    println!("{}", HbValue::String("".into()));
    println!("{}", (HbValue::String("Average: ".into()) + hb_str((ntotal.clone() / anomes.hb_len()), HbValue::Nil, HbValue::Nil)));
    if ((ntotal.clone() / anomes.hb_len()) >= HbValue::Integer(90)) {
        println!("{}", HbValue::String("Grade: A".into()));
    } else if ((ntotal.clone() / anomes.hb_len()) >= HbValue::Integer(80)) {
        println!("{}", HbValue::String("Grade: B".into()));
    } else {
        println!("{}", HbValue::String("Grade: C".into()));
    }
    return;
}

fn maxscore(mut aarr: HbValue) -> HbValue {
    let mut nmax = aarr.hb_get_val(HbValue::Integer(1).clone());
    let mut i = HbValue::Integer(0);
    for i in hb_range(HbValue::Integer(2), aarr.hb_len(), HbValue::Integer(1)) {
        if (aarr.hb_get_val(i.clone()) > nmax.clone()) {
            nmax = aarr.hb_get_val(i.clone());
        }
    }
    return nmax;
    HbValue::Nil
}

fn proc(mut nvalor: HbValue, mut nlocal: HbValue, mut nquantidade: HbValue, mut errado: HbValue) {
    let mut anomes = hb_array![];
    let mut ascores = hb_array![];
    let mut i = HbValue::Integer(0);
    let mut ntotal = HbValue::Integer(0);
    let mut amax = hb_array![HbValue::Integer(1), HbValue::Integer(10), HbValue::Integer(15)];
    let mut cnome = HbValue::String("".into());
    let mut getlist = hb_array![];
    anomes.hb_aadd(HbValue::String("Alice".into()));
    anomes.hb_aadd(HbValue::String("Bob".into()));
    anomes.hb_aadd(HbValue::String("Charlie".into()));
    anomes.hb_aadd(HbValue::String("Blink".into()));
    ascores.hb_aadd(HbValue::Integer(92));
    ascores.hb_aadd(HbValue::Integer(87));
    ascores.hb_aadd(HbValue::Integer(95));
    if (nvalor.clone() == HbValue::Integer(0)) {
        nlocal = HbValue::Integer(5);
        errado = HbValue::String("TEXT".into());
    }
    println!("{}", HbValue::String("=== Score Report ===".into()));
    println!("{}", HbValue::String("".into()));
    for i in hb_range(HbValue::Integer(1), anomes.hb_len(), HbValue::Integer(1)) {
        cnome = anomes.hb_get_val(i.clone());
        ntotal = (ntotal.clone() + ascores.hb_get_val(i.clone()));
        println!("{}", ((cnome.clone() + HbValue::String(": ".into())) + hb_str(ascores.hb_get_val(i.clone()), HbValue::Nil, HbValue::Nil)));
    }
    println!("{}", HbValue::String("".into()));
    println!("{}", (HbValue::String("Average: ".into()) + hb_str((ntotal.clone() / anomes.hb_len()), HbValue::Nil, HbValue::Nil)));
    if ((ntotal.clone() / anomes.hb_len()) >= HbValue::Integer(90)) {
        println!("{}", HbValue::String("Grade: A".into()));
    } else if ((ntotal.clone() / anomes.hb_len()) >= HbValue::Integer(80)) {
        println!("{}", HbValue::String("Grade: B".into()));
    } else {
        println!("{}", HbValue::String("Grade: C".into()));
    }
    return;
}
