// Generated by SWed (Shipwrecked) — do not edit manually.
#![allow(non_snake_case, unused_mut, unused_variables, unused_imports)]

use swed_rt::{HbValue, HbArray};
use swed_rt::{pub_declare, pub_get, pub_set, memvar_assign, memvar_get}; 

macro_rules! hb_array {
    ( $($e:expr),* $(,)? ) => {{
        let mut __a = HbArray::new();
        $( __a.hb_aadd($e); )*
        __a
    }};
}

fn main() {
    let _: HbValue = (|| {
        let mut nkey = HbValue::Nil;
        let mut nlinha = HbValue::Nil;
        let mut ncoluna = HbValue::Nil;
        let mut alinha = HbValue::Nil;
        let mut ccor = HbValue::Nil;
        let mut apecaselecionada = HbValue::Nil;
        let mut atabuleiro = iniciatabuleiro();
        nlinha = HbValue::Integer(5).clone();
        ncoluna = HbValue::Integer(5).clone();
        print!("\x1B[2J\x1B[H");
        ccor = HbValue::String("R/W,N/GR*,,,N/W*".into());
        while HbValue::Logical(true) {
            desenhatabuleiro(atabuleiro);
            alinha = atabuleiro.hb_get_val(nlinha.clone());
            desenha(alinha, nlinha, ncoluna, ccor);
            nkey = hb_inkey(HbValue::Integer(0));
            if (hb_lastkey() == HbValue::Integer(27)) {
                break;
            }
            if (nkey.clone() == HbValue::Integer(5)) {
                nlinha = hb_max(HbValue::Integer(1), { nlinha -= HbValue::Integer(1); nlinha.clone() });
                if (!posicaovalida(nlinha, ncoluna)) {
                    { let old = nlinha.clone(); nlinha += HbValue::Integer(1); old };
                }
            } else if (nkey.clone() == HbValue::Integer(24)) {
                nlinha = hb_min(HbValue::Integer(9), { nlinha += HbValue::Integer(1); nlinha.clone() });
                if (!posicaovalida(nlinha, ncoluna)) {
                    { let old = nlinha.clone(); nlinha -= HbValue::Integer(1); old };
                }
            } else if (nkey.clone() == HbValue::Integer(19)) {
                ncoluna = hb_max(HbValue::Integer(1), { ncoluna -= HbValue::Integer(1); ncoluna.clone() });
                if (!posicaovalida(nlinha, ncoluna)) {
                    { let old = ncoluna.clone(); ncoluna += HbValue::Integer(1); old };
                }
            } else if (nkey.clone() == HbValue::Integer(4)) {
                ncoluna = hb_min(HbValue::Integer(9), { ncoluna += HbValue::Integer(1); ncoluna.clone() });
                if (!posicaovalida(nlinha, ncoluna)) {
                    { let old = ncoluna.clone(); ncoluna -= HbValue::Integer(1); old };
                }
            } else if (nkey.clone() == HbValue::Integer(13)) {
                if (ccor.clone() == HbValue::String("R/W,N/GR*,,,N/W*".into())) {
                    ccor = HbValue::String("G/W,N/GR*,,,N/W*".into());
                    apecaselecionada = hb_array![nlinha, ncoluna];
                } else {
                    possocomerpeca(atabuleiro, nlinha, ncoluna, apecaselecionada);
                    ccor = HbValue::String("R/W,N/GR*,,,N/W*".into());
                }
            }
        }
        return HbValue::Integer(0);
        HbValue::Nil
    })();
}

fn posicaovalida(mut nlinha: HbValue, mut ncoluna: HbValue) -> HbValue {
    return (((nlinha.clone() > HbValue::Integer(2)) && (nlinha.clone() < HbValue::Integer(6))) || ((ncoluna.clone() > HbValue::Integer(2)) && (ncoluna.clone() < HbValue::Integer(6))));
    HbValue::Nil
}

fn iniciatabuleiro() -> HbValue {
    let mut atabuleiro = HbValue::Nil;
    let mut alinha = HbValue::Nil;
    let mut nlinha = HbValue::Nil;
    let mut ncoluna = HbValue::Nil;
    atabuleiro = hb_array(HbValue::Integer(7));
    for nlinha in hb_range(HbValue::Integer(1), atabuleiro.hb_len(), 1) {
        alinha = hb_array(HbValue::Integer(7));
        atabuleiro.hb_set_val(nlinha, alinha);
        for ncoluna in hb_range(HbValue::Integer(1), alinha.hb_len(), 1) {
            if posicaovalida(nlinha, ncoluna) {
                alinha.hb_set_val(ncoluna, HbValue::Integer(1));
            } else {
                alinha.hb_set_val(ncoluna, HbValue::Integer(3));
            }
        }
    }
    atabuleiro.hb_set_nested(HbValue::Integer(4), HbValue::Integer(4), HbValue::Integer(2));
    return atabuleiro;
    HbValue::Nil
}

fn desenhatabuleiro(mut atabuleiro: HbValue) {
    let mut alinha = HbValue::Nil;
    let mut nlinha = HbValue::Nil;
    let mut ncoluna = HbValue::Nil;
    let mut ccor = HbValue::Nil;
    ccor = hb_setcolor();
    for nlinha in hb_range(HbValue::Integer(1), atabuleiro.hb_len(), 1) {
        alinha = atabuleiro.hb_get_val(nlinha.clone());
        for ncoluna in hb_range(HbValue::Integer(1), alinha.hb_len(), 1) {
            desenha(alinha, nlinha, ncoluna, ccor);
        }
    }
    return;
}

fn desenha(mut alinha: HbValue, mut nlinha: HbValue, mut ncoluna: HbValue, mut ccor: HbValue) {
    let mut adesenha = HbValue::Nil;
    adesenha = hb_array(HbValue::Integer(3));
    adesenha.hb_set_val(HbValue::Integer(3), hb_space(HbValue::Integer(1)));
    adesenha.hb_set_val(HbValue::Integer(1), hb_chr(HbValue::Integer(219)));
    adesenha.hb_set_val(HbValue::Integer(2), hb_chr(HbValue::Integer(176)));
    println!("{}", hb_replicate(adesenha.hb_get_val(alinha.hb_get_val(ncoluna.clone()).clone()), HbValue::Integer(3)));
    return;
}

fn possocomerpeca(mut atabuleiro: HbValue, mut nlinha: HbValue, mut ncoluna: HbValue, mut apecaselecionada: HbValue) {
    if ((nlinha.clone() == apecaselecionada.hb_get_val(HbValue::Integer(1).clone())) && ((ncoluna.clone() - apecaselecionada.hb_get_val(HbValue::Integer(2).clone())) == HbValue::Integer(2))) {
        if (((atabuleiro.hb_get_val(nlinha.clone()).hb_get_val((ncoluna.clone() - HbValue::Integer(0)).clone()) == HbValue::Integer(2)) && (atabuleiro.hb_get_val(nlinha.clone()).hb_get_val((ncoluna.clone() - HbValue::Integer(1)).clone()) == HbValue::Integer(1))) && (atabuleiro.hb_get_val(nlinha.clone()).hb_get_val((ncoluna.clone() - HbValue::Integer(2)).clone()) == HbValue::Integer(1))) {
            atabuleiro.hb_set_nested(nlinha, (ncoluna.clone() - HbValue::Integer(0)), HbValue::Integer(1));
            atabuleiro.hb_set_nested(nlinha, (ncoluna.clone() - HbValue::Integer(1)), HbValue::Integer(2));
            atabuleiro.hb_set_nested(nlinha, (ncoluna.clone() - HbValue::Integer(2)), HbValue::Integer(2));
        }
    } else if ((nlinha.clone() == apecaselecionada.hb_get_val(HbValue::Integer(1).clone())) && ((ncoluna.clone() - apecaselecionada.hb_get_val(HbValue::Integer(2).clone())) == (-HbValue::Integer(2)))) {
        if (((atabuleiro.hb_get_val(nlinha.clone()).hb_get_val((ncoluna.clone() + HbValue::Integer(0)).clone()) == HbValue::Integer(2)) && (atabuleiro.hb_get_val(nlinha.clone()).hb_get_val((ncoluna.clone() + HbValue::Integer(1)).clone()) == HbValue::Integer(1))) && (atabuleiro.hb_get_val(nlinha.clone()).hb_get_val((ncoluna.clone() + HbValue::Integer(2)).clone()) == HbValue::Integer(1))) {
            atabuleiro.hb_set_nested(nlinha, (ncoluna.clone() + HbValue::Integer(0)), HbValue::Integer(1));
            atabuleiro.hb_set_nested(nlinha, (ncoluna.clone() + HbValue::Integer(1)), HbValue::Integer(2));
            atabuleiro.hb_set_nested(nlinha, (ncoluna.clone() + HbValue::Integer(2)), HbValue::Integer(2));
        }
    } else if ((ncoluna.clone() == apecaselecionada.hb_get_val(HbValue::Integer(2).clone())) && ((nlinha.clone() - apecaselecionada.hb_get_val(HbValue::Integer(1).clone())) == HbValue::Integer(2))) {
        if (((atabuleiro.hb_get_val((nlinha.clone() - HbValue::Integer(0)).clone()).hb_get_val(ncoluna.clone()) == HbValue::Integer(2)) && (atabuleiro.hb_get_val((nlinha.clone() - HbValue::Integer(1)).clone()).hb_get_val(ncoluna.clone()) == HbValue::Integer(1))) && (atabuleiro.hb_get_val((nlinha.clone() - HbValue::Integer(2)).clone()).hb_get_val(ncoluna.clone()) == HbValue::Integer(1))) {
            atabuleiro.hb_set_nested((nlinha.clone() - HbValue::Integer(0)), ncoluna, HbValue::Integer(1));
            atabuleiro.hb_set_nested((nlinha.clone() - HbValue::Integer(1)), ncoluna, HbValue::Integer(2));
            atabuleiro.hb_set_nested((nlinha.clone() - HbValue::Integer(2)), ncoluna, HbValue::Integer(2));
        }
    } else if ((ncoluna.clone() == apecaselecionada.hb_get_val(HbValue::Integer(2).clone())) && ((nlinha.clone() - apecaselecionada.hb_get_val(HbValue::Integer(1).clone())) == (-HbValue::Integer(2)))) {
        if (((atabuleiro.hb_get_val((nlinha.clone() + HbValue::Integer(0)).clone()).hb_get_val(ncoluna.clone()) == HbValue::Integer(2)) && (atabuleiro.hb_get_val((nlinha.clone() + HbValue::Integer(1)).clone()).hb_get_val(ncoluna.clone()) == HbValue::Integer(1))) && (atabuleiro.hb_get_val((nlinha.clone() + HbValue::Integer(2)).clone()).hb_get_val(ncoluna.clone()) == HbValue::Integer(1))) {
            atabuleiro.hb_set_nested((nlinha.clone() + HbValue::Integer(0)), ncoluna, HbValue::Integer(1));
            atabuleiro.hb_set_nested((nlinha.clone() + HbValue::Integer(1)), ncoluna, HbValue::Integer(2));
            atabuleiro.hb_set_nested((nlinha.clone() + HbValue::Integer(2)), ncoluna, HbValue::Integer(2));
        }
    }
    return;
}
