//! Gerador de testes de regressão Rust a partir de um manifesto `.mkh`.
//!
//! Lê um [`Manifest`] (produzido por [`crate::analyse_file`]) e emite um arquivo
//! `<out_dir>/<stem>_regressao.rs` com:
//!
//! - Um `fn setup_globals()` que injeta valores-padrão nas variáveis PUBLIC/MEMVAR
//!   detectadas, usando [`swed_rt::publics_var::public_store`].
//! - Para cada `FUNCTION`: um teste *golden* (parâmetros tipados via Hungarian) e
//!   um teste *nil_params* (fuzzing básico de NIL).
//! - Para cada `PROCEDURE`: um teste *smoke* e (se tiver params) *nil_params*.
//!
//! Os valores-padrão e o assert de retorno são inferidos via notação húngara:
//! prefixo do nome do parâmetro (`nValor` → `HbValue::Float(1.0)`) ou, para
//! nomes em UPPERCASE sem case original, pelo primeiro caractere (`N` → Float).

use std::fs;
use std::path::{Path, PathBuf};

use crate::types::{HbType, Manifest, ParamDef, Symbol, SymbolKind};

// ── API pública ───────────────────────────────────────────────────────────────

/// Gera `<out_dir>/<stem>_regressao.rs` com testes de regressão de caixa-preta.
///
/// O arquivo inclui o `.rs` transpilado via `#[path = "../<stem>.rs"] mod transpiled;`
/// (caminho ajustável se a estrutura de diretórios diferir).
///
/// # Errors
/// Retorna `Err(String)` se não conseguir criar o diretório ou escrever o arquivo.
pub fn generate_tests(
    prg_path: &Path,
    manifest: &Manifest,
    out_dir: &Path,
) -> Result<PathBuf, String> {
    let stem = prg_path
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| format!("nome de arquivo inválido: {}", prg_path.display()))?;

    fs::create_dir_all(out_dir)
        .map_err(|e| format!("mkdir {}: {e}", out_dir.display()))?;

    let out_file = out_dir.join(format!("{stem}_regressao.rs"));
    let content = render(stem, manifest);

    fs::write(&out_file, &content)
        .map_err(|e| format!("write {}: {e}", out_file.display()))?;

    Ok(out_file)
}

// ── Renderer principal ────────────────────────────────────────────────────────

fn render(stem: &str, m: &Manifest) -> String {
    let mut buf = String::with_capacity(4096);

    emit_header(&mut buf, m);

    let globals: Vec<&Symbol> = m
        .symbols
        .iter()
        .filter(|s| {
            matches!(s.kind, SymbolKind::Public | SymbolKind::Memvar)
                && s.scope == "GLOBAL"
        })
        .collect();

    let functions: Vec<&Symbol> = m
        .symbols
        .iter()
        .filter(|s| matches!(s.kind, SymbolKind::Function))
        .collect();

    let procedures: Vec<&Symbol> = m
        .symbols
        .iter()
        .filter(|s| matches!(s.kind, SymbolKind::Procedure))
        .collect();

    let mod_name = format!("test_{}_regressao", to_snake_case(stem));

    buf.push_str("#[cfg(test)]\n");
    buf.push_str(&format!("mod {mod_name} {{\n"));

    emit_imports(&mut buf, stem);
    emit_setup_fn(&mut buf, &globals);

    for func in &functions {
        emit_function_tests(&mut buf, func);
    }
    for proc in &procedures {
        emit_procedure_tests(&mut buf, proc);
    }

    if functions.is_empty() && procedures.is_empty() {
        buf.push_str("    // Nenhuma FUNCTION ou PROCEDURE encontrada neste .prg.\n");
    }

    buf.push_str("}\n");
    buf
}

// ── Seções do arquivo gerado ──────────────────────────────────────────────────

fn emit_header(buf: &mut String, m: &Manifest) {
    buf.push_str("// GENERATED by swed_testgen — DO NOT EDIT MANUALLY\n");
    buf.push_str(&format!("// Source : {}\n", m.source_path));
    buf.push_str(&format!("// MD5    : {}\n", m.md5));
    buf.push_str("//\n");
    buf.push_str("// Ajuste o #[path] abaixo se o .rs transpilado não estiver em ../\n\n");
}

fn emit_imports(buf: &mut String, stem: &str) {
    buf.push_str(&format!("    #[path = \"../{stem}.rs\"]\n"));
    buf.push_str("    #[allow(dead_code, unused_imports, non_snake_case)]\n");
    buf.push_str("    mod transpiled;\n");
    buf.push_str("    #[allow(unused_imports)]\n");
    buf.push_str("    use transpiled::*;\n");
    buf.push_str("    use swed_rt::HbValue;\n");
    buf.push_str("    use swed_rt::publics_var::public_store;\n\n");
}

/// Emite `fn setup_globals()` que limpa o store e injeta valores-padrão.
///
/// Prioridade de inferência do valor:
/// 1. `symbol.hb_type` — detectado no nome **original** antes de UPPERCASE (preciso)
/// 2. Heurística de um char no nome UPPERCASE — fallback quando o original era ALLCAPS
fn emit_setup_fn(buf: &mut String, globals: &[&Symbol]) {
    buf.push_str("    fn setup_globals() {\n");
    buf.push_str("        public_store().write().unwrap().clear();\n");

    if globals.is_empty() {
        buf.push_str("        // Nenhuma PUBLIC/MEMVAR global detectada neste .prg.\n");
    } else {
        for g in globals {
            let val = if g.hb_type.is_some() {
                default_value(&g.hb_type)
            } else {
                default_for_uppercase(&g.name)
            };
            buf.push_str(&format!(
                "        public_store().write().unwrap().set({:?}, {val}); // AJUSTE: valor representativo\n",
                g.name
            ));
        }
    }

    buf.push_str("    }\n\n");
}

/// Emite testes *golden* + *nil_params* para uma FUNCTION.
fn emit_function_tests(buf: &mut String, func: &Symbol) {
    let rust_fn = to_snake_case(&func.name);

    buf.push_str(&format!(
        "    // ── FUNCTION {} {}\n\n",
        func.name,
        "-".repeat(50usize.saturating_sub(func.name.len() + 14))
    ));

    // Golden: argumentos com valores-padrão tipados
    buf.push_str("    #[test]\n");
    buf.push_str(&format!("    fn test_{rust_fn}_golden() {{\n"));
    buf.push_str("        setup_globals();\n");
    let args = typed_args(&func.params);
    buf.push_str(&format!("        let result = {rust_fn}({args});\n"));

    // Preferência: hb_type do manifesto (detectado antes de UPPERCASE) → heurística
    let assert_expr = return_assert_from_type(&func.hb_type)
        .or_else(|| return_assert_for(&func.name));
    match assert_expr {
        Some(expr) => buf.push_str(&format!(
            "        assert!({expr}, \"retorno inesperado: {{result:?}}\");\n"
        )),
        None => {
            buf.push_str(
                "        // AJUSTE: adicione assert sobre `result` conforme comportamento esperado.\n",
            );
            buf.push_str("        let _ = result;\n");
        }
    }
    buf.push_str("    }\n\n");

    // NIL fuzzing: Harbour não pode panic com NIL em parâmetros
    buf.push_str("    #[test]\n");
    buf.push_str(&format!("    fn test_{rust_fn}_nil_params() {{\n"));
    buf.push_str(
        "        // Semântica Harbour: NIL em qualquer parâmetro não deve causar panic.\n",
    );
    buf.push_str("        setup_globals();\n");
    let nil = nil_args(func.params.len());
    buf.push_str(&format!("        let _ = {rust_fn}({nil});\n"));
    buf.push_str("    }\n\n");
}

/// Emite testes *smoke* + *nil_params* para uma PROCEDURE.
fn emit_procedure_tests(buf: &mut String, proc: &Symbol) {
    let rust_fn = to_snake_case(&proc.name);

    buf.push_str(&format!(
        "    // ── PROCEDURE {} {}\n\n",
        proc.name,
        "-".repeat(50usize.saturating_sub(proc.name.len() + 16))
    ));

    buf.push_str("    #[test]\n");
    buf.push_str(&format!("    fn test_{rust_fn}_smoke() {{\n"));
    buf.push_str("        setup_globals();\n");
    let args = typed_args(&proc.params);
    buf.push_str(&format!("        {rust_fn}({args}); // smoke: não deve panic\n"));
    buf.push_str("    }\n\n");

    if !proc.params.is_empty() {
        buf.push_str("    #[test]\n");
        buf.push_str(&format!("    fn test_{rust_fn}_nil_params() {{\n"));
        buf.push_str("        setup_globals();\n");
        let nil = nil_args(proc.params.len());
        buf.push_str(&format!("        {rust_fn}({nil});\n"));
        buf.push_str("    }\n\n");
    }
}

// ── Inferência de tipo e valores-padrão ──────────────────────────────────────

/// Valor-padrão de teste para um argumento, baseado no `HbType` inferido.
fn default_value(hb_type: &Option<HbType>) -> &'static str {
    match hb_type {
        Some(HbType::Float) => "HbValue::Float(1.0)",
        Some(HbType::Integer) => "HbValue::Integer(1)",
        Some(HbType::Character) => "HbValue::String(\"TEST\".into())",
        Some(HbType::Logical) => "HbValue::Logical(true)",
        Some(HbType::Date) => "HbValue::Date(0)",
        _ => "HbValue::Nil",
    }
}

/// Valor-padrão para uma variável PUBLIC cujo nome está em UPPERCASE.
///
/// Como o analisador normaliza para UPPERCASE, a Hungarian detection completa
/// não é possível. Usa heurística de um caractere.
fn default_for_uppercase(name: &str) -> &'static str {
    match name.chars().next() {
        Some('N') | Some('F') => "HbValue::Float(1.0)",
        Some('C') => "HbValue::String(\"TEST\".into())",
        Some('L') => "HbValue::Logical(true)",
        Some('D') => "HbValue::Date(0)",
        _ => "HbValue::Nil",
    }
}

/// Expressão de assert para retorno de FUNCTION a partir do `HbType` do manifesto.
///
/// Usa o tipo detectado **antes** do UPPERCASE — mais preciso que a heurística de 1 char.
fn return_assert_from_type(hb_type: &Option<HbType>) -> Option<&'static str> {
    match hb_type {
        Some(HbType::Float) | Some(HbType::Integer) => {
            Some("matches!(result, HbValue::Float(_) | HbValue::Integer(_))")
        }
        Some(HbType::Character) => Some("matches!(result, HbValue::String(_))"),
        Some(HbType::Logical) => Some("matches!(result, HbValue::Logical(_))"),
        _ => None,
    }
}

/// Expressão de assert para o retorno de uma FUNCTION (heurística de 1 char no nome UPPERCASE).
///
/// Fallback quando `hb_type` é `None` — ocorre quando o nome original era ALLCAPS
/// e a Hungarian detection não pôde ser aplicada.
fn return_assert_for(fn_name: &str) -> Option<&'static str> {
    match fn_name.chars().next() {
        Some('N') | Some('F') => {
            Some("matches!(result, HbValue::Float(_) | HbValue::Integer(_))")
        }
        Some('C') => Some("matches!(result, HbValue::String(_))"),
        Some('L') => Some("matches!(result, HbValue::Logical(_))"),
        _ => None,
    }
}

/// Constrói a lista de argumentos tipados a partir dos `ParamDef`.
fn typed_args(params: &[ParamDef]) -> String {
    params
        .iter()
        .map(|p| default_value(&p.hb_type))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Constrói uma lista de N argumentos `HbValue::Nil`.
fn nil_args(n: usize) -> String {
    vec!["HbValue::Nil"; n].join(", ")
}

// ── to_snake_case (espelha scope::to_snake_case do crate swed) ───────────────

/// Converte um identificador Harbour para snake_case Rust.
///
/// Idêntico a `swed::scope::to_snake_case` — duplicado aqui para evitar
/// dependência circular entre crates.
pub(crate) fn to_snake_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    let chars: Vec<char> = s.chars().collect();
    for (i, &ch) in chars.iter().enumerate() {
        let prev_lower = i > 0 && chars[i - 1].is_ascii_lowercase();
        if ch.is_ascii_uppercase() && prev_lower {
            out.push('_');
        }
        out.push(ch.to_ascii_lowercase());
    }
    let mut result = String::with_capacity(out.len());
    let mut prev_under = false;
    for ch in out.chars() {
        if ch.is_alphanumeric() {
            result.push(ch);
            prev_under = false;
        } else if !prev_under {
            result.push('_');
            prev_under = true;
        }
    }
    result.trim_matches('_').to_string()
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{HbType, ParamDef, Symbol, SymbolKind};

    fn func_sym(name: &str, hb_type: Option<HbType>, params: Vec<ParamDef>) -> Symbol {
        Symbol {
            name: name.into(),
            kind: SymbolKind::Function,
            scope: "GLOBAL".into(),
            line: 1,
            attributes: vec![],
            conditional: false,
            hb_type,
            params,
        }
    }

    fn pub_sym(name: &str, hb_type: Option<HbType>) -> Symbol {
        Symbol {
            name: name.into(),
            kind: SymbolKind::Public,
            scope: "GLOBAL".into(),
            line: 1,
            attributes: vec![],
            conditional: false,
            hb_type,
            params: vec![],
        }
    }

    #[test]
    fn snake_case_allcaps() {
        assert_eq!(to_snake_case("CALCIMPOSTO"), "calcimposto");
        assert_eq!(to_snake_case("CALC_IMPOSTO"), "calc_imposto");
    }

    #[test]
    fn snake_case_camel() {
        assert_eq!(to_snake_case("CalcImposto"), "calc_imposto");
        assert_eq!(to_snake_case("nValor"), "n_valor");
    }

    #[test]
    fn default_value_by_type() {
        assert_eq!(default_value(&Some(HbType::Float)), "HbValue::Float(1.0)");
        assert_eq!(default_value(&Some(HbType::Character)), "HbValue::String(\"TEST\".into())");
        assert_eq!(default_value(&Some(HbType::Logical)), "HbValue::Logical(true)");
        assert_eq!(default_value(&None), "HbValue::Nil");
    }

    #[test]
    fn default_for_uppercase_heuristic() {
        assert_eq!(default_for_uppercase("NEMPRESA"), "HbValue::Float(1.0)");
        assert_eq!(default_for_uppercase("CUSUARIO"), "HbValue::String(\"TEST\".into())");
        assert_eq!(default_for_uppercase("LATIVO"), "HbValue::Logical(true)");
        assert_eq!(default_for_uppercase("XRAW"), "HbValue::Nil");
    }

    #[test]
    fn return_assert_n_prefix() {
        assert!(return_assert_for("NCALC").is_some());
        assert!(return_assert_for("CGET").is_some());
        assert!(return_assert_for("GETDATA").is_none()); // 'G' sem prefixo → None
    }

    #[test]
    fn typed_args_mixed() {
        let params = vec![
            ParamDef::new("nValor"),  // Float
            ParamDef::new("cNome"),   // Character
            ParamDef::new("lAtivo"),  // Logical
        ];
        let args = typed_args(&params);
        assert_eq!(args, "HbValue::Float(1.0), HbValue::String(\"TEST\".into()), HbValue::Logical(true)");
    }

    #[test]
    fn nil_args_count() {
        assert_eq!(nil_args(3), "HbValue::Nil, HbValue::Nil, HbValue::Nil");
        assert_eq!(nil_args(0), "");
    }

    #[test]
    fn render_contains_function_tests() {
        // hb_type=Float (detectado do nome original antes de UPPERCASE) + NEMPRESA com hb_type
        let m = Manifest {
            source_path: "prog.prg".into(),
            md5: "abc".into(),
            symbols: vec![
                func_sym("NCALCIMPOSTO", Some(HbType::Float), vec![
                    ParamDef::new("nBase"),
                    ParamDef::new("nAliq"),
                ]),
                pub_sym("NEMPRESA", Some(HbType::Float)),
            ],
            usages: vec![],
        };
        let out = render("prog", &m);

        assert!(out.contains("mod test_prog_regressao"));
        assert!(out.contains("#[path = \"../prog.rs\"]"));
        assert!(out.contains("fn test_ncalcimposto_golden()"));
        assert!(out.contains("fn test_ncalcimposto_nil_params()"));
        assert!(out.contains("ncalcimposto(HbValue::Float(1.0), HbValue::Float(1.0))"));
        assert!(out.contains("ncalcimposto(HbValue::Nil, HbValue::Nil)"));
        // hb_type=Float → assert preciso (via return_assert_from_type, não heurística)
        assert!(out.contains("matches!(result, HbValue::Float(_)"));
        // PUBLIC global: hb_type=Float → HbValue::Float(1.0)
        assert!(out.contains("\"NEMPRESA\""));
        assert!(out.contains("HbValue::Float(1.0)"));
    }

    #[test]
    fn render_manifest_type_beats_heuristic() {
        // Função "CUSUARIO" começa com 'C' (heurística → String),
        // mas hb_type=Logical (detectado do original "lUsuario") → deve gerar assert Logical
        let m = Manifest {
            source_path: "t.prg".into(),
            md5: "x".into(),
            symbols: vec![
                func_sym("CUSUARIO", Some(HbType::Logical), vec![]),
            ],
            usages: vec![],
        };
        let out = render("t", &m);
        assert!(out.contains("matches!(result, HbValue::Logical(_))"));
        // NÃO deve conter o assert de String (heurística seria 'C' → String)
        assert!(!out.contains("matches!(result, HbValue::String(_))"));
    }

    #[test]
    fn render_procedure_no_assert_on_return() {
        let m = Manifest {
            source_path: "proc.prg".into(),
            md5: "def".into(),
            symbols: vec![Symbol {
                name: "INITAPP".into(),
                kind: SymbolKind::Procedure,
                scope: "GLOBAL".into(),
                line: 1,
                attributes: vec![],
                conditional: false,
                hb_type: None,
                params: vec![ParamDef::new("cConfig")],
            }],
            usages: vec![],
        };
        let out = render("proc", &m);

        assert!(out.contains("fn test_initapp_smoke()"));
        assert!(out.contains("fn test_initapp_nil_params()"));
        assert!(!out.contains("assert!(matches!(result"));
    }

    #[test]
    fn render_empty_prg() {
        let m = Manifest {
            source_path: "empty.prg".into(),
            md5: "000".into(),
            symbols: vec![],
            usages: vec![],
        };
        let out = render("empty", &m);
        assert!(out.contains("Nenhuma FUNCTION ou PROCEDURE"));
    }

    #[test]
    fn setup_fn_uses_hb_type_over_heuristic() {
        // pub_sym com hb_type=Character deve gerar String, não Float (que seria a heurística se 'C' mas a var fosse "NXXX")
        let g = pub_sym("NXXX", Some(HbType::Character)); // nome começa com N mas hb_type=Character
        let globals = vec![&g];
        let mut buf = String::new();
        emit_setup_fn(&mut buf, &globals);
        // hb_type=Character → String, não Float (que seria a heurística de 'N')
        assert!(buf.contains("\"TEST\""));
        assert!(!buf.contains("Float(1.0)"));
    }

    #[test]
    fn setup_fn_clears_store() {
        let globals = vec![];
        let mut buf = String::new();
        emit_setup_fn(&mut buf, &globals);
        assert!(buf.contains("public_store().write().unwrap().clear()"));
    }
}
