[package]
name         = "swed_db"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
description  = "Shipwrecked database engine — RDD / DBF access layer"

[dependencies]
swed_rt  = { path = "../swed_rt" }
thiserror = "1.0.69"
byteorder = "1.5"

[lints]
workspace = true
