[package]
name         = "swed_db"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
description  = "Shipwrecked database engine — RDD / DBF access layer"

[dependencies]
swed_rt   = { workspace = true }
thiserror = { workspace = true }
byteorder = { workspace = true }

[lints]
workspace = true
