// Generated by SWed (Shipwrecked) — do not edit manually.
#![allow(non_snake_case, unused_mut, unused_variables, unused_imports)]

use swed_rt::{HbValue, HbArray};
use swed_rt::{pub_declare, pub_get, pub_set, memvar_assign, memvar_get}; 

macro_rules! hb_array {
    ( $($e:expr),* $(,)? ) => {{
        let mut __a = HbArray::new();
        $( __a.hb_aadd($e); )*
        __a
    }};
}

fn main() -> HbValue {
    let mut nkey = HbValue::Nil;
    let mut nlinha = HbValue::Nil;
    let mut ncoluna = HbValue::Nil;
    let mut alinha = HbValue::Nil;
    let mut ccor = HbValue::Nil;
    let mut apecaselecionada = HbValue::Nil;
    let mut atabuleiro = iniciatabuleiro();
    NLINHA = HbValue::Integer(5).clone();
    NCOLUNA = HbValue::Integer(5).clone();
    print!("\x1B[2J\x1B[H");
    ccor = HbValue::String("R/W,N/GR*,,,N/W*".into());
    while HbValue::Logical(true) {
        nkey = inkey(HbValue::Integer(0));
        if (lastkey() == HbValue::Integer(27)) {
            break;
        }
    }
    return HbValue::Integer(0);
    HbValue::Nil
}
