// Generated by SWed (Shipwrecked) — do not edit manually.
#![allow(non_snake_case, unused_mut, unused_variables, unused_imports)]

use swed_rt::{HbValue, HbArray};
use swed_rt::{pub_declare, pub_get, pub_set, memvar_assign, memvar_get}; 

macro_rules! hb_array {
    ( $($e:expr),* $(,)? ) => {{
        let mut __a = HbArray::new();
        $( __a.hb_aadd($e); )*
        __a
    }};
}

fn main() -> HbValue {
    let mut bflag = HbValue::Logical(true);
    while bflag {
        bflag = HbValue::Logical(false);
    }
    return HbValue::Integer(0);
    HbValue::Nil
}
